= Identifying APIs to Govern

APIs that meet the filter criteria in API Governance profiles become _governed APIs_. 
Identify the APIs to govern before creating your governance profiles to help ensure that:

* You are governing only the APIs that you want to govern.
* API owners are ready for governance before they start receiving conformance notifications.

== Add Tags and Categories to APIs in Exchange

To identify sets of APIs to govern, apply tags and categories to the API assets in Exchange. You can then select tags and categories as filter criteria when you create your governance profiles. 

* To add asset tags, see xref:exchange::to-describe-an-asset.adoc#add-and-remove-asset-tags[Add and Remove Asset Tags in Exchange].

* To add categories, see xref:exchange::to-describe-an-asset#add-and-remove-categories.adoc[Add and Remove Categories in Exchange].

[[select-and-add-tags]]
== Select and Add Tags in Governance Profiles

When you create or update a profile, you can filter the list of tags to find and select any not initially shown on the page. You can also add tag names in governance profiles if you have not yet added those tags to APIs in Exchange. 

To select and add tags in profiles:

. When creating or updating a profile, navigate to the *Define Filter Criteria* page.
+
. Expand the *General > Tags* section.  
+
The most frequently used tags are shown by default.
+
. Start typing a tag name in the search field to filter the list of tags.
+
. If you don't see a tag you want to use, type a tag name in the search field and press enter to add the tag.

== See Also

* xref:create-profiles.adoc[Applying Governance Rulesets to Specified APIs]
* xref:index.adoc[API Governance Overview]