= Adding External API Sources

Before you can begin discovering APIs, you must add the external API sources from which you want to discover the APIs. 

== Before You Begin Adding an API Source

When you add an AWS source, API Discovery authenticates to AWS using specific authentication information. Ensure that you have these available before proceeding. See <<tips-for-aws-auth>>.

== Add an AWS API Source 

To add an AWS API source:

. In API Governance, select *API Discovery*.
. Select the *API Sources* tab.
. Click *Add API Source*. 
. Follow the UI prompts to enter the information in the following screens:
** <<select-a-system>>
** <<authenticate>>
** <<set-default-values>>
** <<general-information>>

// Screenshot of the Add API Source page (with callouts)

include::_partials/api-discovery-console-scaps-callouts.adoc[tag=api-discovery-add-source-page]

[[select-a-system]]
=== Select a System

AWS is the only system available for the pilot.

[[authenticate]]
=== Authenticate to AWS

Authenticate to AWS using your
access key ID, secret access key, and region. You must configure these in AWS before adding them in API Discovery. See <<tips-for-aws-auth>>.

After the initial authentication, API Discovery stores the encrypted information but cannot retrieve it for display. The authentication remains as configured until you type in the authentication credentials fields again. 

[[set-default-values]]
=== Set Default Values

Set default values for all of the APIs from each source so that you can filter and manage them more easily. This information is defined in Exchange as part of the APIs' catalog information. 

Values include:

* Contact Name
+
Enter a default contact name to use for all APIs from this source.
* Contact Email
+
Enter a default contact name to use for all APIs from this source.
* Tags
+ 
Click in the field to select existing tags or start typing to add new tags.
* Categories
+ 
Select from the listed catagories.

[[general-information]]
=== Specify General Information

Specify additional general information, such as a unique name and whether to scan immediately to discover external APIs for this external source. 

// Need to get and add whatever they can add or change here

[[tips-for-aws-auth]]
== Tips for Getting Your AWS Authentication Information

API Discovery uses your IAM access keys to authenticate to AWS. You must enter a valid access key ID, secret access key, and region to authenticate to AWS from API Discovery.

Verify your access key information by using it to log in to AWS before you enter it in API Discovery.

Control access using an IAM policy in AWS that allows read only access to the AWS API Gateway. Example settings are:

[%header,cols="35a,65a"]
|===
|Parameter |Value
| "Effect" | "Allow"
| "Action" | "apigateway:GET"
| "Resource" | "arn:aws:apigateway:*::/*"
|===

For detailed documentation on configuring IAM access keys and policies, refer to https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Managing access keys for IAM users^] and https://docs.aws.amazon.com/IAM/latest/UserGuide/access_controlling.html[Controlling access to AWS resources using policies^] in the AWS documentation.

// Get other tips to add

// == Troubleshoot Add Sources

// xxx

// == See Also

// xxx xref to AWS auth doc page xxx