= API Governance Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint API Governance is a component of the Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. API Governance helps you improve your organization's API quality by enabling you to identify conformance issues and take steps to resolve them. 

In the API Governance console, you add _governance rulesets_ to _governance profiles_ to apply the governance rulesets to multiple APIs across your organization. The API governance console then provides you with an overview of conformance for all governed APIs.
You can monitor your APIs' conformance and notify developers to help improve the conformance.

API developers or architects can apply the governance rulesets, which are published as assets in Anypoint Exchange, directly to API definitions as dependencies in API Designer during the API design phase. Noncorformance messages are shown in the *Project Errors* section of API Designer. 

== API Governance Concepts

Following are the concepts you need to know to use API Governance.

=== Governance Profiles

A governance profile applies chosen governance rulesets to a select group of APIs. The API definitions are validated
against the governance rulesets. 

A governance profile has two statuses, Normal and At Risk, which are based on the percentage
of conformant APIs in the governance profile.

* *Normal:* More than 70% of APIs are conformant
* *At Risk:* Less than 70% of APIs are conformant

=== Governance Rulesets

Governance rulesets are collections of rules, or guidelines, that can be applied over the metadata extracted from any
REST API definition in the Anypoint Platform. Some examples of governance rulesets are internal and external best
practice guidelines and industry-specific government standards. 

=== Governed APIs

API definitions are governed if they are identified by the selection criteria of at least one of the governance profiles. 

=== API Conformance

API conformance indicates whether a governed API definition passes all of the required rules in one ore more governance rulesets. If an API definition is included in multiple governance profiles, it must pass all of the rulesets in all of those profiles to be conformant. 

NOTE: API conformance applies only to API definitions that are published in Exchange as REST APIs.

=== Conformance Status

The status of your API definitions' conformance to selected rulesets, as configured in your governance profiles.

== See Also

* xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project]
* xref:exchange::to-describe-an-asset.adoc#add-and-remove-asset-tags[Adding and Removing Asset Tags in Exchange]
* xref:exchange::to-manage-categories.adoc[Managing Categories]