= Anypoint API Governance Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint API Governance is a component of the Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. API Governance helps you improve your organization's API quality by enabling you to identify conformance issues and take steps to resolve them. The console provides you with an overview of conformance for all governed APIs and enables you to notify developers to help improve API conformance.

To use API Governance, you add _governance rulesets_ to _governance profiles_ to apply the governance rulesets to multiple APIs across your organization. After the governance profiles have been applied to your APIs, you monitor your APIs' conformance to those governance rulesets on the API Governance console.

API developers or architects can apply the governance rulesets, which are published as assets in Anypoint Exchange, directly to API definitions as dependencies in API Designer during the API design phase. Noncorformance messages are shown in the *Project Errors* section of API Designer. 

== API Governance Concepts

Following are the concepts you need to know to use API Governance.

=== Governance Profiles

A governance profile applies chosen governance rulesets to a select group of APIs. The API definitions are validated
against the governance rulesets. 

A governance profile has two statuses, Normal and At Risk, which are based on the percentage
of conformant APIs in the governance profile.

* *Normal:* More than 70% of APIs are conformant
* *At Risk:* Less than 70% of APIs are conformant

=== Governance Rulesets

Governance rulesets are collections of rules, or guidelines, that can be applied over the metadata extracted from any
REST API definition in the Anypoint Platform. Governance rulesets can include internal or external best
practice guidelines and industry-specific government standards. You can create custom governance rulesets using
AML (Anything Modeling Language), a declarative language for defining metadata documents.

=== API Conformance

API conformance indicates whether an API definition passes all of the required rules included in one ore more governance rulesets. An API definition is only validated by governance rulesets included in governance profiles that also include that API definition. Since API definitions can be included in one or
multiple governance profiles, an API definition could be `Not Conformant` even if it passes governance rulesets from one governance profile. 

NOTE: API conformance applies only to API definitions that are published in Exchange as REST APIs.

=== Conformance Status

The status of your API definitions' conformance to selected rules, as configured in your governance profiles.

=== Anypoint API Governance Console

The main UI for Anypoint API Governance where you can view governance profile statuses, API conformance across governance profiles, and nonconformance by severity across governance profiles. You can also add, update, and delete governance profiles from this page.

== See Also

* xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project]
* xref:exchange::to-describe-an-asset.adoc#add-and-remove-asset-tags[Adding and Removing Asset Tags in Exchange]
* xref:exchange::to-manage-categories.adoc[Managing Categories]