= Governing APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint API Governance is a component of the Anypoint Platform that
allows you to apply governance rules to your APIs as part of the
API lifecycle. Governance rules can include internal or external best
practice guidelines or industry-specific government standards.
You can apply these reusable groups of rules, or governance rulesets,
directly to API definitions during the API design phase. Later, you can add
these same governance rulesets to Governance Profiles and apply the Governance Profiles to multiple APIs across
your organization. Once the Governance Profiles have been applied to your APIs, you can
then monitor your APIs' conformance to those governance rulesets on the API Governance console.

API Governance is tightly integrated with the following tools:

* xref:design-center::index.adoc[Anypoint Design Center (Design Center)], where Governance
  Rulesets are applied to API definitions (as dependencies)
* xref:exchange::index.adoc[Anypoint Exchange (Exchange)], where governance rulesets are catalogued and discovered

== API Governance Concepts

=== Governance Profiles

A Governance Profile applies chosen governance rulesets to a select group of APIs. The API definitions are validated
against the governance rulesets. 

A Governance Profile has two statuses, Normal and At Risk, which are based on the percentage
of conformant APIs in the Governance Profile.

* *Normal:* More than 70% of APIs are conformant
* *At Risk:* Less than 70% of APIs are conformant

=== governance rulesets

Governance rulesets are collections of rules, or guidelines, that can be applied over the metadata extracted from any
REST API definition in the Anypoint Platform. Governance rulesets can include internal or external best
practice guidelines and industry-specific government standards. You can create custom governance rulesets using
AML(Anything Modeling Language), a declarative language for defining metadata documents.

=== API Conformance

API conformance is whether an API definition passes all of the required rules included in
one ore more governance rulesets. An API definition is only validated by governance rulesets included in Governance
Profiles that also include that API definition. Since API definitions can be included in one or
multiple Governance Profiles, an API definition could be Not Conformant even if it passes
governance rulesets from one Governance Profile. 

NOTE: API conformance only applies to API definitions that are cataloged in Exchange as REST APIs

=== Conformance Posture

The status of your API definitions' conformance to selected rules, as configured in your Governance Profiles.

=== API Governance Console

The main UI for API Governance where you can view Governance Profile statuses, API conformance
across Governance Profiles, and nonconformance by severity across Governance Profiles. You can
also add, update, and delete Governance Profiles from this page.
