= API Declaration Reference

API Discovery maps your discovered API properties to Anypoint Platform API properties by making opinionated assumptions about what the AWS properties represent. API information is represented in Anypoint Platform by a proprietary Anypoint Platform API declarative language. Because not all of the discovered API properties have an equivalent in Anypoint Platform, a subset of the properties is mapped.

[[view-api-declaration]]
== View the Mapping of API Information from AWS to Anypoint Platform

When you select a discovered API, the details show the API properties in the raw declarative language. You cannot update this information, but you can use it to understand how the API properties are interpreted. The mapping can also help you write custom governance rulesets for your discovered APIs. See xref:create-custom-rulesets.adoc[].

The following examples show how the sections of the generated API declaration map to the equivalent in AWS.

[[api-environment-declaration]]
=== AWS Environment Information

The AWS environment cannot be mapped directly to an equivalent in API Discovery, because an AWS environment has a different meaning and purpose than an Anypoint Platform environment. Therefore, API Discovery maps the AWS environment to a tag in the discovered API.

The following example shows how the AWS environment information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: Environment <2>
metadata: <3>
  name: v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of environment is saved as AWS metadata in API Discovery because there isn't an equivalent in Anypoint Platform.
.. Metadata from the AWS API.

[[api-environment-binding-declaration]]
=== AWS Environment Binding Information

The AWS environment cannot be mapped directly to an equivalent in API Discovery.

The following example shows how AWS environment binding information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: EnvironmentBinding <2>
spec:
  targetEnvironmentRef: <2>
    name: v1-rcizkl
  targetRef: <3>
    name: uqzxgsgcg6-v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of API binding from the AWS API.
.. Target environment reference from AWS.
.. Target spec reference from AWS.

[[api-policy-binding-declaration]]
=== AWS Policy Bindings Information

The AWS policy bindings information is shown in the declaration.

The following example shows how AWS services information is represented in the API declaration for a discovered API. If there are multiple services, there is a section for each one. This example just shows one.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: Service <2>
metadata:
  name: uqzxgsgcg6-/history-get-service <3>
  labels: <4>
    aws.amazon.com/arn: arn:AWS:apigateway:US_EAST_2::/restapis/uqzxgsgcg6/resources/cx8i3f/methods/get/integration
    aws.amazon.com/region: us-east-2
    aws.amazon.com/resourceId: cx8i3f
    aws.amazon.com/method: get
    aws.amazon.com/partition: AWS
    aws.amazon.com/resource: apigateway-integration
spec:
  address: MOCKED
----
[calloutlist]
.. API version from the AWS API.
.. Kind of service from the AWS API.
.. Service name in AWS.
.. Labels.

[[api-services-declaration]]
=== AWS Services Information

The AWS services information is shown in the declaration.

The following example shows how AWS policy binding information is represented in the API declaration for a discovered API. If there are multiple policy bindings, there is a section for each one. This example just shows one.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: PolicyBinding <2>
metadata:
  name: uqzxgsgcg6-v1-rcizkl-account-level-rate-limiting <3>
spec:
  policyRef:
    name: aws-rate-limiting <4>
  config:
    burstLimit: 5000 <5>
    rateLimit: 10000.0 <6>
  order: 1
  targetRef:
    name: uqzxgsgcg6-v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of policy binding from the AWS API.
.. Policy metadata name in AWS.
.. Policy reference name in AWS.
.. Burst limit.
.. Rate limit.


[[api-instance-declaration]]
=== API Instance Information

APIs might have multiple instances. Each instance is represented by its own section in the API declaration.

The following example shows how AWS instance information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: ApiInstance <2>
metadata: <3>
  name: uqzxgsgcg6-v1-rcizkl
  labels:
    aws.amazon.com/id: uqzxgsgcg6
    aws.amazon.com/resource: apigateway
    aws.amazon.com/stage: v1
    mulesoft.com/apiinstance-id: v1
    aws.amazon.com/region: us-east-2
    aws.amazon.com/partition: AWS
    aws.amazon.com/endpointConfiguration: REGIONAL
spec: <4>
  address: https://uqzxgsgcg6.execute-api.us-east-2.amazonaws.com/v1
----
[calloutlist]
.. API version from the AWS API.
.. Kind of API from the AWS API.
.. Metadata from the AWS API.
.. Specification URL address in AWS based on the AWS API information and region used to authenticate to API Discovery.

// API Discovery stores API information in a declarative language format so that other Anypoint Catalog component can interpret the information. The declarative language parameters that API Discovery uses are shown in the following sections.

// include::_partials/api-discovery-declaration-ref.adoc[leveloffset=+1]

== See Also

* xref:publish-discovered-apis.adoc[]
* xref:create-custom-rulesets.adoc[]