= Troubleshooting Anypoint CLI

If you encounter errors when attempting to run Anypoint CLI commands, troubleshoot them as follows.

== Before You Begin Troubleshooting

Ensure you are using the latest version of `anypoint-cli-v4`. If not, install the latest version before continuing. Refer to xref:anypoint-cli::install.adoc[].

[[cli-upload-dupl-error]]
== Status Code 409 Error When Uploading

An error `Request failed with status code 409` when using the `exchange asset upload` command to publish a ruleset typically indicates that you are attempting to upload a duplicate asset to Exchange.

To resolve this issue:

* Change the command to specify a unique ruleset asset identifier.  
** To publish a new version of the ruleset, change the version part of the asset identifier. For example, change `1.0.0` in the original command: 
+
----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----
+
To `1.0.1` in the updated command:
+
----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.1 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----

** To create a new asset, change the asset ID part of the asset identifier. For example, change `my-auth-best-practices` in the original command: 
+
----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----
+
To `my-new-auth-best-practices` in the updated command:
+
----
anypoint-cli-v4 exchange asset upload my-new-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----

[[asset-type-error]]
== Error Determining Asset Type

There are several causes for the following error:

`Error: Could not determine asset type, step: Publishing asset`

To troubleshoot this issue, consider some typical causes:

* Specifying a type but uploading more than one file type. For example, if you are uploading a ruleset and its documentation, do not use the `--type` flag, because the type of `ruleset` is inferred from the classifier of the first file in the `--files` flag and the documentation is uploaded as `custom` type.
* Including properties in `exchange.json` or `--properties` that are incorrect.
+
The `exchange.json` file is optional when uploading an asset, because the required properties are either included or are inferred from parameters, flags, or options. If you download a ruleset project on which to base your custom ruleset, do one of the following:
+
** Remove the `exchange.json` file from your working folder or project.
** Update the properties in the `exchange.json` file to match your custom ruleset's asset ID, name, main file, and so on.

[[generic-publish-error]]
== Unable to Publish 

A non-specific publishing error similar to `unable to publish` might occur when you're using the `exchange asset upload` command to upload a custom ruleset and its documentation. If you upload using the wrong syntax, you might inadvertently publish the ruleset as Custom type instead of Ruleset type. If this happens, you cannot republish the ruleset as the Ruleset type under the same name, even if you change the version. 

To republish the ruleset in this situation, you must change the name of the ruleset and try uploading again with the proper command syntax. For example, change `my-auth-best-practices` in the original command: 

----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----

To `my-new auth-best-practices` in the updated command:

----
anypoint-cli-v4 exchange asset upload my-new-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----

[[parse-properties-error]]
== Error Parsing Properties

When using Anypoint CLI commands that pass JSON properties from Microsoft Windows, you might get an error similar to the following:
----
 »  Error: Parsing --properties
 »   Unexpected token ' in JSON at position 0
----

To resolve this issue:

Escape the JSON text using the backslash character (`\`). For example, change `"` and `/` in the original command: 

----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml","docs.zip":"/myRulesetFolder/ruleset.doc.zip"}'
----

To `\"` and `\/` in the updated command:

----
anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{\"ruleset.yaml\":\"\/myRulesetFolder\/mynewruleset.yaml\",\"docs.zip\":\"\/myRulesetFolder\/ruleset.doc.zip\"}'
----

[[misc-errors]]
== Miscellaneous Errors

The commands are parsed for specific information and if anything isn't recognized or is misinterpreted in the command, the error message might be misleading or vague. 

To troubleshoot errors that aren't obvious:

* Ensure that you are entering the command flags and options as documented.
* Ensure that you have specified everything in the command using the proper case, including the command itself, flags, classifiers, options, folder names, and file names. Commands are case-sensitive. 
* Ensure that you are entering your own information in option values. Most command examples cannot be run verbatim. You must use your own values for parameters and options, including organization ID, environment ID, host ID, asset identifier GAV (group ID/asset ID/ version), and folder and file names.
* Ensure that you are specifying the proper folders for files in the command or that you have changed to the working directory where they're located.
* Search the https://help.mulesoft.com[MuleSoft Help Center^] for similar errors.

== See Also

* xref:cli-command-list.adoc[]
* xref:anypoint-cli::install.adoc[]
* xref:anypoint-cli::intro.adoc[]