= Sending Conformance Notifications

You can send notifications automatically or manually by configuring them in the API Governance console or by using Anypoint CLI. 

Each email notifications includes:

* The name of the API that is not conformant
* Which governance rulesets the API failed
* Links to open the API in Exchange and to view the code in Design Center   

[[send-auto-notifs]]
== Send Automated Conformance Notifications

If you want to automatically send notifications when the latest version of an API becomes non-conformant, enable and configure the notifications. 

NOTE: Notifications are sent only if there is a valid contact email address configured for the selected recipient.

Automated notifications are sent for each ruleset that has a new conformance failure when the conformance status changes during validation. A notification is sent for a specific API only the first time that version of the API fails conformance to a specific ruleset. 

Following are the changes that might result in notifications: 

. Updating a governance profile, including adding or removing rulesets 
. Publishing a new version of an API 
. Changing tags on an API 
. Updating governance rulesets 

=== Enable and Configure Notifications in the Console

To enable and configure conformance notifications in the console:

. In the API Governance console, while creating or updating a profile, use the *Next* and *Previous* buttons to navigate to the *Notifications* page of the profile for which you want to enable notifications. 
. If it is not already selected, select *Enabled* for *Nonconformance notification*.
. Select a recipient:
+
* *API Publisher*: Email the API publisher by using the email address specified in the listed Anypoint Platform account
* *API Contact*: Email the contact specified in the asset in Exchange
* *Others*: Email to a comma-separated list of email addresses

=== Enable and Configure Notifications Using the CLI

To enable and configure conformance notifications in the CLI:

* When creating or updating a profile using the `governance create profile` or `governance update profile` commands, use the following options to enable notifications:
+
----
--notify-publisher  
--notify-contact 
--notify-others a@a.a,b@b.com
----

See xref:create-profiles.adoc#create-profile-cli[Create a Governance Profile Using the API Governance CLI] or  xref:update-profiles.adoc#update-profile-cli[Update a Governance Profile Using the API Governance CLI].

[[send-manual-notifs]]
== Send Notifications to API Owners Manually

If you want to notify API owners for any reason, such as when an API is not conformant or you made changes to the profile, you can send them an email notification directly from the profile. 

To send a notification email to the API owner: 

. In the API Governance console, select a governance profile. 
. Click the *Notify Owner* icon.
. Select a recipient:
+
* *API Publisher*: Email the API publisher by using the email address specified in the listed Anypoint Platform account
* *API Contact*: Email the contact specified in the asset in Exchange
* *Others*: Email to a comma-separated list of email addresses
. Review the email text and click *Notify Owner*.

== See Also

* xref:create-profiles.adoc[Applying Governance Rulesets to Specified APIs]