= Sending Conformance Notifications

You can send notifications automatically by configuring them in the API Governance console. Alternatively, you can send the notifications manually from a governance profile.

Email notifications include:

* The name of the APIs that are not conformant
* Which governance rulesets the APIs failed
* The number and types of rules that failed (violation, warning, and information)
* Links from which to act on the issues, such as API details in Exchange and code in Design Center 

[[send-auto-notifs]]
== Send Automated Conformance Notifications

If you want to automatically send notifications when the latest version of an API becomes non-conformant, enable the *Nonconformance notification* in the API Governance console and select the recipients. 

NOTE: Notifications are sent only if there is a valid contact email address configured for the selected recipient.

Automated notifications are sent for each ruleset that has a new conformance failure when the conformance status changes during validation. A notification is sent for a specific API only the first time that version of the API fails conformance to a specific ruleset. 

Following are the changes that might result in notifications: 

. Updating a governance profile, including adding or removing rulesets 
. Publishing a new version of an API 
. Changing tags on an API 
. Updating governance rulesets 

To configure and enable conformance notifications:

. In the API Governance console, while creating or updating a profile, use the *Next* and *Previous* buttons to navigate to the *Notifications* page of the profile for which you want to enable notifications. 
. Select a recipient:
+
* *API Publisher*: Email the API publisher by using the email address specified in the listed Anypoint Platform account
* *API Contact*: Email the contact specified in the asset in Exchange
* *Others*: Email to a comma-separated list of email addresses
. Set the slider to *Enabled*.

[[send-manual-notifs]]
== Send Notifications to API Owners

When you notice an API is not conformant, you might want to send the API owner an email notification. 

NOTE: You can send emails to API owners from profiles even when there are no conformance issues. 

To send a notification email to the API owner: 

. In the API Governance console, select a governance profile. 
. Click the *Notify Owner* icon.
. Select a recipient:
+
* *API Publisher*: Email the API publisher by using the email address specified in the listed Anypoint Platform account
* *API Contact*: Email the contact specified in the asset in Exchange
* *Others*: Email to a comma-separated list of email addresses
. Review the email text and click *Notify Owner*.

NOTE: 

* The *API Publisher* selection is disabled if there is not a valid contact email address for the API publisher in their Anypoint Platform profile. 
* The *API Contact* selection is disabled if there is not a valid email address for the API contact in Exchange. 

== See Also

* xref:exchange::to-describe-an-asset.adoc[Describe an Asset]