= Creating Custom Governance Rulesets

MuleSoft provides several rulesets in Exchange, such as Anypoint API Best Practices, OpenAPI Best Practices, OWASP API Security Top 10, and Authentication Security Best Practices governance rulesets. 

Submit your ideas for rulesets you would like MuleSoft to provide in future releases on the https://help.mulesoft.com/s/ideas[MulesSoft Ideas Portal].

== Create Custom Rulesets by Modifying Provided Rulesets

If you want to create custom governance rulesets based on rulesets that are already in Exchange, download and modify the rulesets and then upload them as new assets. This is the best approach if a provided ruleset meets most of your needs and you need to make only a few changes.

To create a custom ruleset based on one already in Exchange:

. Download the ruleset from Exchange.
. Modify the ruleset YAML file. For example, update severity values or delete rules you do not want to use.
. Validate the changes using the `governance validate` command. See <<validate-ruleset>>.
. Generate the ruleset file as an asset document. See <<generate-ruleset-doc>>.
. Publish your custom ruleset as a new asset using the Exchange UI or the `anypoint-cli exchange asset uploadv2` command. See <<publish-to-exchange>>.

== Create Completely New Custom Rulesets

If you want a custom ruleset that cannot be created by modifying one of the provided rulesets:

. First search the https://help.mulesoft.com/s/ideas[MulesSoft Ideas Portal] for ideas for new rulesets that have already been submitted.
. If you do not find your idea there, consider submitting your idea in the MuleSoft Ideas Portal.

NOTE: Similarly to custom code and configurations, rulesets that you create are not considered supported MuleSoft products. For assistance with issues with these custom rulesets, post an issue in the Github repository for the https://github.com/aml-org/amf-custom-validator[AMF Custom Validator^].

If you are interested in learning more about how rulesets are written, see the https://a.ml/docs/amf/using-amf/amf_custom_validation[AMF Custom Validation section^] in the AML Open Source project. 

[[publish-to-exchange]]
== Publish a Custom governance ruleset Asset in Exchange

//include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]

You can publish a ruleset to Exchange as you do any other asset: 

* To upload your custom ruleset using the Exchange UI, see xref:exchange::to-create-an-asset#create-an-api-asset[Create an Asset].

* To upload your custom ruleset using the CLI, use the `exchange asset uploadv2` command. In the following example, the zipped YAML ruleset file is specified in `--files.ruleset.zip ~/temp/ruleset.yaml.zip`.

If you want to generate and include the documentation for the ruleset as part of the published asset, see <<generate-ruleset-doc>> before you run the upload command. In the following example, the zipped ruleset documentation file is specified in the second file option, `--files.docs.zip ~/temp/ruleset.doc.zip`.

To validate your ruleset locally before you upload it, see <<validate-ruleset>>.

*Example command:*

`anypoint-cli exchange asset uploadv2 --name "cli ruleset asset" --description "cli ruleset asset description" --properties.mainFile ruleset.yaml --files.ruleset.zip ~/temp/ruleset.yaml cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset.doc.zip`

[[generate-ruleset-doc]]
== Generate Documentation for a Ruleset File to Upload to Exchange

Use the following command to generate a documentation zip file for a ruleset YAML file. The resulting documentation `zip` file can then be used in an Exchange asset upload using the `--files.docs.zip` option.

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

[[governance-document]]
=== governance document

`> governance document [options] <ruleset> <file>`

This command creates the documentation for an API Governance ruleset definition `zip` file that you want to upload and publish to Exchange. 

*Example command:*
`governance document ~/temp/ruleset.yaml ~/temp/ruleset.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to `/Users/janedoe/temp/prof-1.doc.zip`
----

This command accepts the following options:

Default options: `--help`, `-f`/`--fields` and `-o`/`--output`.
Other options: `--files.docs.zip`

[[validate-ruleset]]
== Validate governance ruleset Format Using the API Governance CLI

To validate the format of your governance ruleset as you develop it, use the following command:

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-ruleset-validate]]
=== governance ruleset validate

`> governance ruleset validate <governance-ruleset>

This command validates the governance ruleset definition's format.

//*Options:* 

//`<ruleset>`     
 
Specify the file location for an api-specification zip to validate with the governance ruleset.	

*Example command:*

`governance ruleset validate ~/temp/prof-1-bad.yaml`

*Example output for a valid ruleset:*

`Ruleset conforms with Dialect`

*Example output for a nonvalid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----