= Applying Governance Rulesets to Specified APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you have identified the APIs in Exchange that 
you want to govern, you are ready to create governance profiles. Governance profiles enable you to select just the sets of APIs that you want to govern for each set of rulesets.

== Create a Governance Profile Using the API Governance Console

The API Governance console UI guides you through creating profiles.

.To create a governance profile using the API Governance console: 

. In *API Governance*, click *New Profile*.
. Follow the UI prompts to enter the following:
+
* *General Information:* Enter a profile name and description that helps others understand what kinds of governance rulesets are included and the kinds of APIs that are governed in this profile.
* *Rulesets*: Select one or more rulesets you want to use to govern your APIs.
* *Filter Criteria*: Specify which APIs your governance profile should be applied to by selecting an API type, tags, and categories. Selections appear in the *Tag* and *Category* fields only if APIs are found that have those tags or categories. See xref:add-tags.adoc[Identifying APIs to Govern].
+
After you select the filters, the APIs are shown that meet the filter criteria that you have selected.
+
CAUTION: If you do not select filter criteria, your governance profile is applied to _all_ of your APIs in Exchange.
Also, the filter criteria is applied to any APIs that are added to Exchange in the future.
+
* *Notifications:* Enable or disable automatic notifications for this profile. The default is enabled. See xref:configure-notifications.adoc#send-auto-notifs[Sending Conformance Notifications]. 
* *Review:* Review your profile and click *Create*.

== Update a Governance Profile Using the API Governance Console

The API Governance console guides you through updating profiles. 

To update governance profile information using the API Governance console: 

. In *API Governance*, in the console *Profiles* tab, click the menu icon at the end of the profile you want to update and select *Edit*.
. You can edit the following items in the governance profile: 
+
* General Information
* Rulesets
* API Criteria
+
. Click *Update Profile*.

NOTE: After you have applied your edits, the total APIs are updated to indicate how many APIs
your governance profile includes based on your updated filter criteria.

== Delete a Governance Profile Using the API Governance Console

The API Governance console guides you through deleting profiles.

To delete a governance profile: 

. In *API Governance*, in the console *Profiles* tab, click the menu icon at the end of the profile you want to update and select *Delete*.
. Click *Yes, Delete*.

== Create Governance Profiles Using the API Governance CLI

If you want to use a command to create an API Governance profile, use the following command:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-profile-create,leveloffset=+1]

[[governance-profile-create]]
=== governance profile create

`> governance profile create [options] <profile-name> <ruleset-gavs>`

This command creates a governance profile. The argument "ruleset-gavs" should be a list of governance ruleset gavs formatted as follows:

<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>

*Options:*

[cols="1,1"]
|===
|Option |Description

|--tags <tags>
|The `tags` argument should be followed by a comma separated list of tags to be applied to the new governance profile, formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument should be followed by a string that is the new governance profile's description.
|===

*Example command:*
 `governance profile create "Profile for Demos" a787009c-c5e5-43a8-8d6a-a4da6d6df0ac/demo/1.0.0 --tags DemosTag --description "This is the demo description"`

*Example output:*
Profile Added
[cols="1,1"]
|===
|Id
|51f9f94c-fb0c-43d4-9895-22c9e64f1537

|Name
|Profile for Demos

|Description
|This is the demo description

|Rulesets
|gav://a787009c-c5e5-43a8-8d6a-a4da6d6df0ac/demo/1.0.0

|Filter
|tag:DemosTag
|===

== List Governance Profile Information Using the API Governance CLI

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-profile-list,leveloffset=+1]

[[governance-profile-list]]
=== governance profile list

`> governance profile list`

This command lists all governance profiles for an organization. You need this information when updating a governance profile.

*Sample output:*

[cols="1,1"]
|===
|Profile Name  |Profile Id

|Best Practices
|8ffd463f-86b2-4132-afc6-44d179209362

|Organization Profile
|eb4f544c-2b97-4f99-97e4-357636228e36

|===

== List Specific Governance Profile Information Using the API Governance CLI

If you want to use a command to list API Governance profile information, use the following command:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-profile-info,leveloffset=+1]

[[governance-profile-info]]
=== governance profile info

`> governance profile info <profile-id>`

This command lists all information for an API governance profile Id.

*Example command:*
 `governance profile info 8ffd463f-86b2-4132-afc6-44d179209362`

*Example output:*

[cols="1,1"]
|===
|Id
|8ffd463f-86b2-4132-afc6-44d179209362

|Name
|Best Practices

|Description
|Our organization best practices

|Rulesets
|gav://a787009c-c5e5-43a8-8d6a-a4da6d6df0ac/best-practices/1.0.0

|Filter
|tag:governed
|===

== Update a Governance Profile Using the API Governance CLI

If you want to use a command to update an API Governance profile, use the following command:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-profile-update,leveloffset=+1]

[[governance-profile-update]]
=== governance profile update

`> governance profile update [options] <profile-id>`

This command updates an existing governance profile. You can update the governance profile's
Governance Rulesets, name, tags, and description.

NOTE: You must know the governance profile Id to edit a Governance Profile. You can get the
governance profile Ids for all of the Governance Profiles for an organization using the
`governance profile list` API Governance CLI command. 

*Options:* 

[cols="1,1"]
|===
|Option |Description

|--ruleset-gavs <ruleset-gavs>
|The `ruleset-gavs` argument should be followed by a list of governance ruleset gavs formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>`. These are the new asset's identifiers.

|--profile-name <profile-name>
|The `profile-name` argument should be followed by a string that is the new Governance Profile name.

|--tags <tags>
|The `tags` argument should be followed by a comma separated list of tags formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument should be followed by a string that is the new Governance Profile description.
|===

*Example command:*
 `governance profile update 51f9f94c-fb0c-43d4-9895-22c9e64f1537 --profile-name "New Name"``

*Example output:*
`Profile updated 51f9f94c-fb0c-43d4-9895-22c9e64f1537`

== Delete a Governance Profile Using the API Governance CLI

To use the CLI to delete an API Governance profile, using the following command:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-profile-delete,leveloffset=+1]

[[governance-profile-delete]]
=== governance profile delete

`> governance profile delete <profile-id>`

This command deletes a specific governance profile.

*Example command:*
`governance profile delete 8ffd463f-86b2-4132-afc6-44d179209362`

*Example output:*
`Profile with id 8ffd463f-86b2-4132-afc6-44d179209362 removed`