= Creating Custom Governance Rulesets

For the Beta, we have added MuleSoft Anypoint API Best Practices,
OpenAPI Best Practices, OWASP API Security Top 10, and Authentication
Security Best Practices Governance Rulesets to Exchange in advance. 

== Customize Governance Rulesets Using AML

In the future, we will provide ways to customize Governance Rulesets. Governance Rulesets are written using AML (Anything Modeling Language), a declarative language for defining metadata documents that can be parsed into graphs of information. For more information on AML, see https://a.ml/docs/aml/aml[What is AML?,,role=external,window=_blank].

== Generate Governance Ruleset Documentation Using the API Governance CLI

This command generates a zip file that can be used in Exchange asset upload with the `--files.docs.zip` option.

=== governance document

`> governance document [options] <ruleset> <file>`

This command creates a Governance Ruleset definition zip file.

*Example command:*
`governance document ~/temp/prof-1.yaml ~/temp/prof-1.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to /Users/janedoe/temp/prof-1.doc.zip
----

== Publish Custom Governance Ruleset Assets in Exchange

If you want to create custom Governance Rulesets in Exchange, you would create them as any other asset.

include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]


=== Publish Custom Governance Rulesets in Exchange using the API Governance CLI

Governance Ruleset upload is completed using Exchange commands and only type was added.

*Example command:*

`exchange asset uploadv2 --name "cli ruleset asset" --description "cli ruleset asset description" --properties.apiVersion v1 --properties.mainFile ruleset-validation.yaml --files.ruleset.zip ~/temp/ruleset-validation.yaml.zip cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset-validation.doc.zip`
