= Creating Custom Governance Rulesets

For the Beta, we have added MuleSoft Anypoint API Best Practices,
OpenAPI Best Practices, OWASP API Security Top 10, and Authentication
Security Best Practices governance rulesets to Exchange in advance. 

== Write Governance Rulesets Using AML

In the future, we will provide links to documentation for writing your own custom governance rulesets
using AML (Anything Modeling Language), a declarative language for defining metadata
documents that can be parsed into graphs of information.

For more information on AML, see https://a.ml/docs/aml/aml[What is AML?,,role=external,window=_blank].

== Create Governance Ruleset Documentation Using the API Governance CLI

This command generates a zip file that can be used in Exchange asset upload with the `--files.docs.zip` option.

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

== governance document

`> governance document [options] <ruleset> <file>`

This command creates an API Governance ruleset definition `zip` file to upload and publish to Exchange.

*Example command:*
`governance document ~/temp/prof-1.yaml ~/temp/prof-1.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to `/Users/janedoe/temp/prof-1.doc.zip`
----

This command accepts the following options:

Default options: `--help`, `-f`/`--fields` and `-o`/`--output`.
Other options: `--files.docs.zip`

== Create Custom Governance Ruleset Assets in Exchange

If you want to create custom governance rulesets based on rulesets that are already in Exchange, you can download and modify the rulesets and then upload them as new assets. 

//include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]

To upload custom assets using the Exchange UI, see xref:exchange::to-create-an-asset#create-an-api-asset[Create an API Asset].

If you want to upload the custom rulesets using the CLI, use the `exchange asset uploadv2` command.

*Example command:*

`exchange asset uploadv2 --name "cli ruleset asset" --description "cli ruleset asset description" --properties.apiVersion v1 --properties.mainFile ruleset-validation.yaml --files.ruleset.zip ~/temp/ruleset-validation.yaml.zip cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset-validation.doc.zip`