= Applying Governance Rulesets to Specified APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You don't want to apply all of your governance rulesets to all of
your APIs. Governance rulesets should be applied based on the types of API
you are governing. 

For instance, for APIs that handle healthcare
information you would want to apply governance rulesets that make sure
all healthcare information standards are followed. Similarly,
for APIs that handle financial information, a different set
of standards would need to be followed. 

Additionally, considering you may have
hundreds of APIs, applying governance rulesets to each individual API is inefficient
and tedious. Instead, using governance profiles, you can apply governance rulesets to
specific types of APIs broadly by combining governance rulesets and API filter criteria.

== Create governance profiles

Once you have access to API Governance and you have created tags to specify the APIs
you want to govern, the next step in governing your APIs is creating a governance profile.
governance profiles pair governance rulesets with API filter criteria to enable you to govern APIs at scale.

.To create a governance profile: 

. Log in to Anypoint Platform using an account that has the API Governance permission.
. In the navigation bar or the main Anypoint Platform page, click *API Governance*.
. Click *New Profile*.
. Enter a governance profile name that helps others understand what kinds of governance rulesets are included in it.
+
You can also add a purpose to explain more about your governance profile, like the kinds of APIs it governs.

. Click *Next*.
. Select one or more governance rulesets you want to use to govern your APIs.
. Click *Next*.
. Specify which APIs your governance profile should be applied to by selecting an API Type and/or Tag(s)
as filter criteria. 
+
The list of APIs shown includes which APIs the governance profile will be applied to based on your filter choices.
+
CAUTION: If you do not select filter criteria, your governance profile will be applied to *ALL* of your APIs in Exchange.
Also, the filter criteria will be applied to any APIs that are added to Exchange in the future.
+

NOTE: The only API Type available for filtering criteria for the beta release is REST APIS.

. Click *Next*.
. Review your profile and click *Create Profile*.

== Create governance profiles Using the API Governance CLI

include::anypoint-cli::partial$api-governance.adoc[tag=governance-console-create,leveloffset=+1]

== List governance profile Information Using the API Governance CLI

include::anypoint-cli::partial$api-governance.adoc[tag=governance-console-list,leveloffset=+1]

== List Specific governance profile Information Using the API Governance CLI

include::anypoint-cli::partial$api-governance.adoc[tag=governance-console-info,leveloffset=+1]

== Update governance profiles

You can update governance profile information after creating them. 

To update governance profile information: 

. Log in to Anypoint Platform using an account that has the API Governance permission.
. In the navigation bar or the main Anypoint Platform page, click *API Governanace*.
. On the Profiles tab of the API Governance console page, click the kebab icon for the
  governance profile you want to update, and select *Edit*.
. You can edit the following items in the governance profile: 
+
* General Information
  * Profile Name
  * Description
* Rulesets
* API Criteria
  * API type
  * Tags
+
NOTE: After you have made your edits, the Total APIs will be updated to indicate how many APIs
your governance profile will include based on your updated filter criteria.

. Click *Update Profile*.

== Update a Governance Profile Using the API Governance CLI

include::anypoint-cli::partial$api-governance.adoc[tag=governance-console-update,leveloffset=+1]

== Delete a Governance Profile

To delete a governance profile: 

. Log in to Anypoint Platform using an account that has the API Governance permission.
. In the navigation bar or the main Anypoint Platform page, click *API Governanace*.
. On the Profiles tab of the API Governance console page, click the kebab icon for the
  governance profile you want to update, and select *Delete*.
. Click *Yes, Delete*.

== Delete a Governance Profile Using the API Governance CLI

include::anypoint-cli::partial$api-governance.adoc[tag=governance-console-delete,leveloffset=+1]