= Creating Custom Governance Rulesets

For the Beta, we have added MuleSoft Anypoint API Best Practices,
OpenAPI Best Practices, OWASP API Security Top 10, and Authentication
Security Best Practices governance rulesets to Exchange in advance. 

== Write Governance Rulesets Using AML

In the future, we will provide links to documentation for writing your own custom governance rulesets
using AML (Anything Modeling Language), a declarative language for defining metadata
documents that can be parsed into graphs of information.

For more information on AML, see https://a.ml/docs/aml/aml[What is AML?,,role=external,window=_blank].

== Create Governance Ruleset Documentation Using the API Governance CLI

Use the following command to generate a zip file that can be used in Exchange asset upload with the `--files.docs.zip` option:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

=== governance document

`> governance document [options] <ruleset> <file>`

This command creates an API Governance ruleset definition `zip` file to upload and publish to Exchange.

*Example command:*
`governance document ~/temp/prof-1.yaml ~/temp/prof-1.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to `/Users/janedoe/temp/prof-1.doc.zip`
----

This command accepts the following options:

Default options: `--help`, `-f`/`--fields` and `-o`/`--output`.
Other options: `--files.docs.zip`

== Create Custom Governance Ruleset Assets in Exchange

If you want to create custom governance rulesets based on rulesets that are already in Exchange, you can download and modify the rulesets and then upload them as new assets. 

//include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]

To upload custom assets using the Exchange UI, see xref:exchange::to-create-an-asset#create-an-api-asset[Create an API Asset].

If you want to upload the custom rulesets using the CLI, use the `exchange asset uploadv2` command.

*Example command:*

`exchange asset uploadv2 --name "cli ruleset asset" --description "cli ruleset asset description" --properties.apiVersion v1 --properties.mainFile ruleset-validation.yaml --files.ruleset.zip ~/temp/ruleset-validation.yaml.zip cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset-validation.doc.zip`

== Validate Governance Ruleset Format Using the API Governance CLI

To test the format of your governance ruleset as you develop it, use the following command:

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-validate]]
== governance validate

`> governance validate [options] <ruleset>`

This command validates the Governance Ruleset definition's format.

*Options:* 

`--spec <api-specification>`     
 
The `spec` command should be followed by a file location for an api-specification zip to validate with the governance ruleset.	

*Example command without api-spec:*

`governance validate ~/temp/prof-1-bad.yaml`

*Example output without api-spec for valid ruleset:*

`Ruleset conforms with Dialect`

*Example output without api-spec for non valid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

*Example command with api-spec:*

`governance validate ~/temp/prof-1.yaml --spec ~/Downloads/positive-1.0.0-raml.zip`

*Example output with a valid api-spec:*

----
Spec conforms with Ruleset

Output with a non valid api-spec:
Ruleset /path/temp/prof-1.yaml
Spec /path/Downloads/negative-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----