= Applying Rulesets to Specified APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You don't want to apply all of your rulesets to all of
your APIs. Rulesets should be applied based on the types of API
you are governing. For instance, for APIs that handle healthcare
information you would want to apply rulesets that make sure
all healthcare information regulations are followed. Similarly,
for APIs that handle financial information, a different set
of regulations would need to be followed.

== Create Governance Profiles

Once you have access to API Governance and you have created tags to specify the APIs
you want to govern, the next step in governing your APIs is creating a governance profile.
Governance profiles pair rulesets with filter criteria to allow you to govern APIs at scale.

.To create a governance profile: 

. Log in to Anypoint Platform using an account that has the API Governance permission
. In the navigation bar or the main Anypoint Platform page, click *API Governanace*.
. Click *New Profile*.
. Enter a profile name that helps others understand what kinds of rulesets are included in it.
+
You can also add a purpose to explain more about your profile, like the kinds of APIs it governs.

. Click *Next*.
. Select one or more rulesets you want to use to govern your APIs.
. Click *Next*.
. Specify which APIs your profile should be applied to by selecting an API Type and/or Tag(s)
as filter criteria. 
+
The list of APIs shown includes which APIs the profile will be applied to based on your filter choices.
+
CAUTION: If you do not select filter criteria, your profile will be applied to *ALL* of your APIs in Exchange.
+

NOTE: The only API Type available for filtering criteria for the beta release is REST APIS.

. Click *Next*.
. Review your profile and click *Create Profile*.

== Create Governance Profiles with the CLI

=== governance console create

`> governance console create [options] <profile-name> <ruleset-gavs>`

This command creates a new profile. The argument "ruleset-gavs" should be a list of ruleset gavs formatted as follows:

<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>

*Options:*

[cols="1,1"]
|===
|Option |Description

|--tags <tags>
|The `tags` argument should be followed by a comma separated list of tags to be applied to the new governance profile, formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument should be followed by a string that is the new governance profile's description.
|===

*Example command:*
 `governance console create "Profile for Demos" a787009c-c5e5-43a8-8d6a-a4da6d6df0ac/demo/1.0.0 --tags DemosTag --description "This is the demo description"`

*Example output:*
Profile Added
[cols="1,1"]
|===
|Id
|51f9f94c-fb0c-43d4-9895-22c9e64f1537

|Name
|Profile for Demos

|Description
|This is the demo description

|Rulesets
|gav://a787009c-c5e5-43a8-8d6a-a4da6d6df0ac/demo/1.0.0

|Filter
|tag:DemosTag
|===

== Update governance profiles

You can update governance profile information after creating them. 

To update governance profile information: 

. Log in to Anypoint Platform using an account that has the API Governance permission
. In the navigation bar or the main Anypoint Platform page, click *API Governanace*.
. On the Profiles tab of the API Governance console page, click the kebab icon for the
  governance profile you want to update, and select *Edit*.
. You can edit the following items in the governance profile: 
+
* General Information
  * Profile Name
  * Description
* Rulesets
* API Criteria
  * API type
  * Tags
+
NOTE: After you have made your edits, the Total APIs will be updated to indicate how many APIs
your governance profile will include based on your updated filter criteria.

. Click *Update Profile*.

== Update governance profiles with the CLI

=== governance console update

`> governance console update [options] <profile-id>`

This command updates a governance profile.

*Options:* 

[cols="1,1"]
|===
|Option |Description

|--ruleset-gavs <ruleset-gavs>
|The `ruleset-gavs` argument should be followed by a list of ruleset gavs formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>`. These will be the new asset's identifiers.

|--profile-name <profile-name>
|The `profile-name` argument should be followed by a string that will be the new governance profile name.

|--tags <tags>
|The `tags` argument should be followed by a comma separated list of tags formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument should be followed by a string that will be the new governance profile description.
|===

*Example command:*
 `governance console update 51f9f94c-fb0c-43d4-9895-22c9e64f1537 --profile-name "New Name"``

*Example output:*
`Profile updated 51f9f94c-fb0c-43d4-9895-22c9e64f1537`

== Delete a Governance Profile

To delete a governance profile: 

. Log in to Anypoint Platform using an account that has the API Governance permission
. In the navigation bar or the main Anypoint Platform page, click *API Governanace*.
. On the Profiles tab of the API Governance console page, click the kebab icon for the
  governance profile you want to update, and select *Delete*.
. Click *Yes, Delete*.

== Delete a Governance Profile with the CLI

=== governance console delete

`> governance console delete <profile-id>`

This command deletes a specific governance profile.

*Example command:*
`governance console delete 8ffd463f-86b2-4132-afc6-44d179209362`

*Example output:*
`Profile with id 8ffd463f-86b2-4132-afc6-44d179209362 removed`