= Creating Custom Governance Rulesets

MuleSoft provides several rulesets in Exchange, such as Anypoint API Best Practices, OpenAPI Best Practices, OWASP API Security Top 10, and Authentication Security Best Practices governance rulesets. 

Submit your ideas for rulesets you would like MuleSoft to provide in future releases on the https://help.mulesoft.com/s/ideas[MulesSoft Ideas Portal].

== Create Custom Rulesets by Modifying Provided Rulesets

If you want to create custom governance rulesets based on rulesets that are already in Exchange, you can download and modify the rulesets and then upload them as new assets. This is the best approach if a provided ruleset meets most of your needs and you just need to make a few changes.

To create a custom ruleset based on one already in Exchange:

. Download the ruleset from Exchange.
. Modify the ruleset YAML file. For example, update severity values or delete rules you do not want to use.
. Validate the changes using the `governance validate` command. See <<validate-ruleset>>.
. Generate the ruleset file as an asset document. See <<generate-ruleset>>.
. Publish your custom ruleset as a new asset using the Exchange UI or the `anypoint-cli exchange asset uploadv2` command. See <<publish-to-exchange>>.

== Write Governance Rulesets Using AML

If you need to create a ruleset that is very different from any of the provided rulesets, you can write your own 
using AML (Anything Modeling Language), a declarative language for defining metadata
documents that can be parsed into graphs of information.

For more information on AML, see https://a.ml/docs/[What is AML?,,role=external,window=_blank].

NOTE: Custom rulesets are not supported by MuleSoft Support. For assistance with an issues with your custom rulesets, you can post an issue on the Github repository for the https://github.com/aml-org/aml-spec[AML Open Source project]. 

[[generate-ruleset]]
== Generate a Ruleset File to Upload to Exchange

Use the following command to generate a zip file that can be used in Exchange asset upload with the `--files.docs.zip` option:

//include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

[[governance-document]]
=== governance document

`> governance document [options] <ruleset> <file>`

This command creates an API Governance ruleset definition `zip` file to upload and publish to Exchange.

*Example command:*
`governance document ~/temp/prof-1.yaml ~/temp/prof-1.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to `/Users/janedoe/temp/prof-1.doc.zip`
----

This command accepts the following options:

Default options: `--help`, `-f`/`--fields` and `-o`/`--output`.
Other options: `--files.docs.zip`

[[publish-to-exchange]]
== Publish a Custom Governance Ruleset Asset in Exchange

//include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]

To upload custom assets using the Exchange UI, see xref:exchange::to-create-an-asset#create-an-api-asset[Create an API Asset].

To upload the custom rulesets using the CLI, use the `exchange asset uploadv2` command.

*Example command:*

`anypoint-cli exchange asset uploadv2 --name "cli ruleset asset" --description "cli ruleset asset description" --properties.apiVersion v1 --properties.mainFile ruleset-validation.yaml --files.ruleset.zip ~/temp/ruleset-validation.yaml.zip cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset-validation.doc.zip`

[[validate-ruleset]]
== Validate Governance Ruleset Format Using the API Governance CLI

To validate the format of your governance ruleset as you develop it, use the following command:

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-ruleset-validate]]
=== governance ruleset validate

`> governance ruleset validate <governance-ruleset>

This command validates the governance ruleset definition's format.

//*Options:* 

//`<ruleset>`     
 
Specify the file location for an api-specification zip to validate with the governance ruleset.	

*Example command:*

`governance ruleset validate ~/temp/prof-1-bad.yaml`

*Example output for a valid ruleset:*

`Ruleset conforms with Dialect`

*Example output for a nonvalid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----