= Validating and Publishing Custom Rulesets

After you create a custom ruleset:

. <<validate-ruleset,Validate>> the ruleset.
. <<generate-ruleset-doc,Generate the documentation>> for the ruleset. 
. <<publish-ruleset,Publish your custom ruleset>> to Exchange as a new asset. 

For an example sequence of commands to validate and publish your rulesets, see <<example-publish-sequence>>.

NOTE: As with custom code and configurations, rulesets are not considered supported MuleSoft products. For help with issues with custom rulesets, post an issue in the https://github.com/aml-org/amf-custom-validator[AMF Custom Validator Github repository^].

[[validate-ruleset]]
== Validate the Ruleset

To validate your governance ruleset as you create it and before you publish it, use the following command:

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-validate,leveloffset=+1]

[[generate-ruleset-doc]]
== Generate the Ruleset Documentation

Use the following command to generate a documentation ZIP file for a ruleset YAML file. The resulting documentation ZIP file can then be used in an Exchange asset upload using the `--files` flag with the `docs.zip` option.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

[[publish-ruleset]]
== Publish the Custom Ruleset

You can publish (upload) a ruleset and its documentation to Exchange using Anypoint CLI. You can't use the Exchange UI to upload ruleset documentation.

You can upload the following in a single upload command:

[%header,cols="20a,40a,40a"]
|===
|Flag and Options|Result|Example
|The ruleset YAML using the `--files` flag with the `"ruleset.yaml"` option.
|This uploads the ruleset information included in the YAML file and ignores any other files detected in the same folder, such as the `exchange.json` file. You can use `--type=ruleset`. If you don't, the type is inferred from the `--files` flag `--ruleset.yaml` option.
|`--files='{"ruleset.yaml":"mynewruleset.yaml", "docs.zip": "ruleset.doc.zip"}'`
|The ruleset ZIP using the `--files` flag with the `"ruleset.zip"` option.
|This uploads the ruleset information included in the YAML file and evaluates other files in the zip file, such as the `exchange.json` file. You can use `--type=ruleset`. If you don't, the type is inferred from the `--files` flag `"ruleset.zip"` option.
|`--files='{"ruleset.zip":"mynewruleset.zip"}'`
|The ruleset YAML and the ruleset documentation ZIP file using the `--files` flag with the `"ruleset.yaml"` and `"docs.zip"` options in the same `--files` flag. 
|This uploads the ruleset YAML information plus the documentation for the ruleset. You must upload the documentation along with the ruleset. You cannot upload documentation separately later, but can add it manually. 
|`--files='{"ruleset.yaml":"mynewruleset.yaml", "docs.zip": "ruleset.doc.zip"}'`
|The ruleset ZIP and the ruleset documentation ZIP file using the `--files` flag with the `"ruleset.zip"` option with the `"docs.zip"` option in the same `--files` flag. 
|This uploads the ruleset ZIP file information, evaluating any `exchange.json` file properties, plus the documentation for the ruleset. You must upload the documentation along with the ruleset. You cannot upload documentation separately later, but can add it manually. 
|`--files='{"ruleset.zip":"mynewruleset.zip", "docs.zip": "ruleset.doc.zip"}'`
|===

=== Guidelines for Ruleset Exchange JSON Files

You can use an `exchange.json` file to define the Exchange settings for rulesets. You can use any of the following properties:

[%header,cols="35a,65a"]
|===
|Property|Description
|main|The main file of your asset. Ensure that this matches the name of your ruleset when publishing a ruleset. 
|name|The artifact name of your asset. You cannot change the name of an asset that's already published. 
|organizationId|The Anypoint Platform organization or business group in which to publish the asset.
|groupId|The Anypoint Platform group in which to publish the asset.
|assetId|The Exchange asset ID assigned to the asset.
|version|The asset version. 
|classifier|The asset type. Use the value `"ruleset"` when publishing a ruleset asset.
|dependencies| Rulesets can have fragments defined as dependencies.
|tags| Tags for ruleset asset's details in Exchange. 
|descriptorVersion|
|===

For example:
----
{ "main":"ruleset.yaml", "name":"My Mule API Management Best Practices", "organizationId":"68ef9520-24e9-4cf2-b2f5-620025690913", "groupId":"68ef9520-24e9-4cf2-b2f5-620025690913", "assetId":"my-mule-api-management-best-practices", "version":"1.0.0", "classifier":"ruleset", "dependencies":[], "tags":["instances"], "descriptorVersion": "1.0.0" }
----

Use the following command documentation as a reference as you upload the ruleset and its documentation to Exchange.

include::anypoint-cli::partial$exchange-assets.adoc[tag=exchange-asset-upload,leveloffset=+1]

[[example-publish-sequence]]
== Example Command Sequence to Validate and Publish

Use the following example sequence to get started validating your ruleset, generating its documentation, and uploading both to Exchange. Replace the details, such as the folder name, ruleset file name, and ruleset documentation ZIP file name, with your own.

[source,console]
----
anypoint-cli-v4 governance:ruleset:validate /myRulesetFolder/mynewruleset.yaml <1>

anypoint-cli-v4 governance:document /myRulesetFolder/mynewruleset.yaml /myRulesetFolder/ruleset.doc.zip <2>

anypoint-cli-v4 exchange asset upload my-auth-best-practices/1.0.0 --name "My Best Practices Ruleset" --description "This ruleset enforces my best practices for APIs." --files='{"ruleset.yaml":"/myRulesetFolder/mynewruleset.yaml", "docs.zip": "/myRulesetFolder/ruleset.doc.zip"}' <3>
----
[calloutlist]
.. Validates the ruleset locally. The ruleset file is `mynewruleset.yaml` in the `/myRulesetFolder/` folder.
.. Generates the documentation ZIP file, `ruleset.doc.zip`, for the ruleset `myruleset.yaml`. Both files are in the `/myRulesetFolder/` folder.
.. Uploads the ruleset, `mynewruleset.yaml`, and its documentation, `ruleset.doc.zip`. Both files are in the `/myRulesetFolder/` folder. 

== See Also

* xref:cli-commands-troubleshoot.adoc[]
* xref:anypoint-cli::exchange-assets.adoc[]