= Validating and Publishing a Custom Ruleset

Before you publish your custom ruleset:

[[validate-ruleset]]
== Validate Governance Ruleset Format Using the API Governance CLI

To validate the format of your governance ruleset as you develop it, use the following command:

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-validate,leveloffset=+1]

[[scaffold-rulesets]]
== Scaffold Rulesets from Data Schemas

To scaffold rulesets from data schemas, use the following command sequence:

. <<inspect-for-api-type>>
. <<initialize-ruleset-from-dataschema>>

[[inspect-for-api-type]]
=== Inspect API Specifications for API Type

Use the following command to inspect API specifications for API type. This helps you determine which data schema to use.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-inspect,leveloffset=+1]

[[generate-ruleset-doc]]
== Generate Documentation for a Ruleset File to Upload to Exchange

Use the following command to generate a documentation ZIP file for a ruleset YAML file. The resulting documentation ZIP file can then be used in an Exchange asset upload using the `--files.docs.zip` option.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-document,leveloffset=+1]

[[publish-ruleset]]
== Publish a Custom Governance Ruleset Asset in Exchange

//include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]

You can publish a ruleset to Exchange as you do any other asset: 

* To upload your custom ruleset using the Exchange UI, see xref:exchange::to-create-an-asset#create-a-ruleset-asset[Create a Ruleset Asset].

* To upload your custom ruleset using the CLI, use the `exchange asset upload` command. In the following example, the zipped YAML ruleset file is specified in `--files.ruleset.zip ~/temp/ruleset.yaml.zip`.

To generate and include the documentation for the ruleset as part of the published asset, see <<generate-ruleset-doc>> before you run the upload command. In the following example, the zipped ruleset documentation file is specified in the second file option, `--files.docs.zip ~/temp/ruleset.doc.zip`.

To validate your ruleset locally before you upload it, see <<validate-ruleset>>.

*Example command:*

`anypoint-cli exchange:asset:upload --name "cli ruleset asset" --description "cli ruleset asset description" --properties.mainFile ruleset.yaml --files.ruleset.zip ~/temp/ruleset.zip cli-ruleset-asset/1.0.0 --files.docs.zip ~/temp/ruleset.doc.zip`