= Creating Custom Rulesets by Modifying Provided Rulesets

To create custom governance rulesets based on rulesets that are already in Exchange, download and modify the rulesets and then upload them as new assets. This is the best approach if a provided ruleset meets most of your needs and you need to make only a few changes. 

To create a custom ruleset based on one already in Exchange, use one of the following approaches:

* <<use-clone-cli>>
* <<manual-edit>>

For an example of the sequence of commands to modify a ruleset, see <<example-publish-sequence>>.

For an example of the before and after of a manually modified ruleset, see <<example-manual-modify>>.

[[use-clone-cli]]
== Change Rule Severity or Enable or Disable Rules Using Anypoint CLI

To create a custom ruleset using Anypoint CLI, use the `governance:ruleset:clone` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-clone,leveloffset=+2]

To list the rules in a ruleset, use the `governance:ruleset:info` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-info,leveloffset=+2]

include::3.x@anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

[[manual-edit]]
== Manually Modify Rulesets

To modify a ruleset manually to create a custom ruleset:

. Download the ruleset from Exchange.
. Modify the ruleset YAML file. For example, update severity values or delete rules you do not want to use.

[[example-modify-sequence]]
== Example Command Sequence to Modify a Ruleset

[source,console]
----
xxx (1)

xxx (2)

xxx (3)
----
[calloutlist]
.. xxx
.. xxx
.. xxx

[[example-manual-modify]]
== Example of a Manually Modified Ruleset

xxx show a side by side comparison of before and after xxx