= Creating Custom Rulesets by Modifying Provided Rulesets

To create custom governance rulesets based on rulesets that are already in Exchange, download and modify the rulesets and then upload them as new assets. This is the best approach if a provided ruleset meets most of your needs and you need to make only a few changes. 

To create a custom ruleset based on one already in Exchange, use one of the following approaches:

* <<list-rules>>
* <<use-clone-cli>>
* <<manual-edit>>

For an example of the sequence of commands to modify a ruleset, see <<example-publish-sequence>>.

For an example of the before and after of a manually modified ruleset, see <<example-manual-modify>>.

[[list-rules]]
== List Ruleset Rules Using Anypoint CLI
To list the rules in a ruleset, use the `governance:ruleset:info` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-info,leveloffset=+2]

[[use-clone-cli]]
== Change Rule Severity or Enable or Disable Rules Using Anypoint CLI

To create a custom ruleset using Anypoint CLI, use the `governance:ruleset:clone` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-clone,leveloffset=+2]

[[example-modify-sequence]]
== Example Command Sequence to Modify a Ruleset

[source,console]
----
anypoint-cli-v4 governance:ruleset:info 68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.2 --remote (1)

anypoint-cli-v4 governance:ruleset:clone ~/MyRulesetFolder/myruleset.yaml 'New Ruleset from Clone' 'Cloned from ruleset.yaml' --warning=operation-default-response,operation-operationId > mynewruleset.yaml (2)

anypoint-cli-v4 governance:ruleset:info MyRulesetFolder/myruleset.yaml (3)
----
[calloutlist]
.. Lists the rules in the published version of a ruleset that you want to modify to create a custom version.
.. Clones the ruleset `ruleset.yaml` and puts the `operation-default-response,operation-operationId` rules in the warning section.
.. Lists the rules in the modified version of the ruleset to verify that the rules are the way you want them.

After you modify the ruleset, validate it, generate its documentation, and publish it as documented in   xref:custom-rulesets-validate-and-publish.adoc[].

[[manual-edit]]
== Manually Modify Rulesets

To modify a ruleset manually to create a custom ruleset:

. Download the ruleset from Exchange.
. Modify the ruleset YAML file. For example, update severity values or delete rules you do not want to use.

After you modify the ruleset, validate it, generate its documentation, and publish it as documented in   xref:custom-rulesets-validate-and-publish.adoc[].

include::3.x@anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]