= Creating Custom Rulesets by Modifying Published Rulesets

If a published ruleset meets most of your needs, consider using it as an example to base your custom ruleset on. 

To create a custom ruleset by modifying a published ruleset:

. Download the ruleset from Exchange using the Anypoint Platform UI.
. Optionally list the rules in the "before" ruleset.
. Clone the ruleset and modify the rules using Anypoint CLI or manually.
. Optionally list the rules in the "after" ruleset.
. Validate the custom ruleset.
. Generate the documentation for the ruleset.
. Publish the customized ruleset as a new ruleset asset along with its associated documentation. 

To create a custom ruleset based on one already in Exchange, use one of the following approaches:

* <<use-clone-cli>>
* <<manual-edit>>

[[use-clone-cli]]
== Change Rule Severity or Enable or Disable Rules Using Anypoint CLI

Watch this video to see how to clone and customize an example ruleset using Anypoint CLI. Use this video along with the documentation to get started downloading an example ruleset, modifying rules using Anypoint CLI, and publishing your customized ruleset. 

++++
include::_partials/api-gov-custom-ruleset-video.html[]
++++

[[list-rules]]
=== List Ruleset Rules Using Anypoint CLI

Optionally use Anypoint CLI to list the rules:

* Before you modify the ruleset to help determine what you want to change (the "before" list)
* After you change the ruleset (the "after" list) to compare to the "before" list and ensure you changed what you meant to change 

TIP: Use the redirection operator (`>` to overwrite or `>>` to append) to write the output of the `info` command to a file for easier comparison.

To list the rules in a ruleset, use the `governance:ruleset:info` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-info,leveloffset=+2]

[[clone-and-modify]]
=== Clone and Modify the Ruleset

To create a custom ruleset using Anypoint CLI, use the `governance:ruleset:clone` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-ruleset-clone,leveloffset=+2]

[[example-modify-sequence]]
== Example Command Sequence to Modify a Ruleset

Use the following example sequence to get started modifying a ruleset. Replace the details, such as the folder name, ruleset file name, and ruleset documentation ZIP file name, with your own.

[source,console]
----
anypoint-cli-v4 governance ruleset info 68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.2 --remote <1>

anypoint-cli-v4 governance ruleset clone ~/MyRulesetFolder/myruleset.yaml 'New Ruleset from Clone' 'Cloned from myruleset.yaml' --warning=operation-default-response,operation-operationId > mynewruleset.yaml <2>

anypoint-cli-v4 governance ruleset info ~/MyRulesetFolder/mynewruleset.yaml <3>
----
[calloutlist]
.. Lists the rules in the published version of a published ruleset that you want to modify to create a custom version.
.. Clones the downloaded ruleset, `myruleset.yaml`, to create a new custom ruleset, `mynewruleset.` Puts the `operation-default-response` and `operation-operationId` rules in the warning section in `mynewruleset`.
.. Lists the rules in the modified version of the ruleset, `mynewruleset.yaml`, to verify that the rules are the way you want them.

include::anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

[[manual-edit]]
== Manually Modify Rulesets

To modify a ruleset manually to create a custom ruleset:

. Download the ruleset from Exchange.
. Modify the ruleset YAML file. For example, update severity values or delete rules you do not want to use.

== Next Steps 

After you modify the ruleset, see xref:custom-rulesets-validate-and-publish.adoc[].

== See Also

* xref:exchange::to-download-an-asset.adoc[]
* xref:anypoint-cli::exchange-assets.adoc[]