= Taking Action from the Dashboard

== Creating Governance Profiles from the Dashboard

The API Governance Dashboard UI guides you through creating profiles. When you take action from the Dashboard to create a profile, your profile is prepopulated with the APIs that match the filter criteria from the Dashboard. 

[[create-profile-unprotected-apis]]
== Create a Governance Profile for Unprotected APIs

If you click *Create Profile* from the *Unprotected APIs* section of the Dashboard, your draft profile is prepopulated with the following:

* The profile name is *Unprotected APIs*.
* All unprotected APIs are included by the filter criteria.
* The *Anypoint Best Practices* and *Authentication Security* rulesets are selected.
* Notifications are enabled for the profile.

* You can change any settings, including selecting rulesets and filter criteria, to further refine the profile.
* You can save the profile as a draft or activate it.
* After you save the profile as a draft, you can view the conformance information for the APIs in the profile.
* After you activate the profile, you can view the conformance information for the APIs in the profile outside of the draft profile view.

You can then review your profile and click *Save as a draft* or *Save as active*:

* Save a profile as draft to test profile settings and review conformance information before showing the conformance information for its targeted APIs outside of the draft profile view.
* Save a profile as active to show the conformance information outside of the draft profile view.

When you save a profile as either draft or active, its targeted APIs become governed.

[[create-profile-production-apis]]
== Create a Governance Profile for APIs in Production

If you click *Create Profile* from the *APIs in Production* section of the Dashboard, your draft profile is prepopulated with the following:

* The profile name is *APIs in Production*.
* APIs with instances in a production environment are included by the filter criteria.
* The *Mule API Management* ruleset is selected.
* Notifications are enabled for the profile.

* You can change any settings, including selecting rulesets and filter criteria, to further refine the profile.
* You can save the profile as a draft or activate it.
* After you save the profile as a draft, you can view the conformance information for the APIs in the profile.
* After you activate the profile, you can view the conformance information for the APIs in the profile outside of the draft profile view.

You can then review your profile and click *Save as a draft* or *Save as active*:

* Save a profile as draft to test profile settings and review conformance information before showing the conformance information for its targeted APIs outside of the draft profile view.
* Save a profile as active to show the conformance information outside of the draft profile view.

When you save a profile as either draft or active, its targeted APIs become governed.
