= Discovering APIs from External Sources

After you have added an API source, you can scan to discover APIs from that source. API Discovery authenticates to AWS before each scan using the authentication information you saved for the source. 

== Scan for APIs from an AWS Source

You can scan immediately after saving your API source or scan later. After the scan completes, you can view the discovered APIs in the *Discovered APIs* page.

After the initial scan and discovery, you can scan a source again to discover new APIs and updates.

NOTE: API Discovery cannot discover APIs that have no stages or an undeployed stage.

To scan for new or updated APIs from an AWS source:

. In API Governance, select *API Discovery*.
. Select the *API Sources* tab.
. For the source for which you want to discover APIs, click *Scan*. 
. Select the *Discovered APIs* tab to view the discovered APIs. 

// Screenshot of the API Discovery console with callouts

include::_partials/api-discovery-console-scaps-callouts.adoc[tag=api-discovery-discovered-apis-tab]

== Improve the API Discovery Results

Because AWS can be configured and used in many different ways, the mapping from AWS API properties to Anypoint Platform API properties might not match what you expect to see. Some ways that you can ensure a better mapping are:

* Review how the AWS API properties map to Anypoint Platform API properties and if feasible, update the API properties in AWS to ensure that the mapping is more accurate upon discovery.
* If you cannot update the properties, after you run the scan to discover the APIs, take time to update  the API properties in API Discovery before publishing the APIs to Exchange.

== Troublehoot the Scan

If the scan fails, the information available in API Discovery might be limited. Some common reasons for failure are:

* A drop in the network during the scan, such as a loss of internet connection. Ensure the connection is established and try the scan again.
* The authentication information for the AWS source is invalid or expired. Edit the AWS source and navigate to the *Authenticate* page to update the authentication information.
* Anypoint Platform cannot add discovered APIs that are not successfully deployed in AWS. Ensure that all of the APIs are deployed in the source you are scanning.
* Work with your AWS administrator to ensure that the APIs in the AWS source are in a valid state to discover. 