= Discovering APIs from External Sources

After you have added an API source, you can scan to discover APIs from that source.

// Screenshot of the API Discovery console with callouts

include::_partials/api-discovery-console-scaps-callouts.adoc[tag=api-discovery-discovered-apis-tab]

== Before You Begin to Discover APIs From AWS Sources

Because AWS can be configured and used in many different ways, the mapping from AWS API properties to Anypoint Platform API properties might not match what you expect to see. Some ways that you can ensure a better mapping are:

* Review how the AWS API properties map to Anypoint Platform API properties and if feasible, update the AWS API properties to ensure that the mapping is more accurate upon discovery.
* If you cannot update the properties, after you run the scan to discover the APIs, take time to resolve the available API settings before publishing the APIs in Exchange.

== Autodiscover APIs from AWS

When you add an AWS source, Anypoint Platform authenticates to AWS using the authentication information you saved for the AWS sources. It scans for APIs using the settings you configured. If successful, the discovered APIs appear in the *Discovered APIs* page.

== Scan for APIs from an AWS Source

After the initial scan, you can scan again to discover new APIs and updates to those you've already discovered.

To scan for new or updated APIs from an AWS source:

. In API Governance, select *API Discovery*.
. Select the *API Sources* tab.
. Beside the source for which you want to discover APIs, click *Scan*. 
. Select the *Discovered APIs* tab to view the discovered APIs. 

== Troublehoot the Scan

If the scan fails, the information available in API Discovery might be limited. Some common reasons for failure are:

* A drop in the network during the scan, such as a loss of internet connection. Ensure the connection is established and try the scan again.
* The authentication information for the AWS source is invalid or expired. Edit the AWS source and navigate to the *Authenticate* page to update the authentication information.
* Anypoint Platform cannot add discovered APIs that are not successfully deployed in AWS. Ensure that all of the APIs are deployed in the source you are scanning.
* Work with your AWS administrator to ensure that the APIs in the AWS source are in a valid state to import. 