= Finding API Conformance Issues in API Definitions

Rulesets can be applied to API definitions as you are authoring them, either in Design Center
or with the API Governance CLI. You can also validate rulesets to make sure they are formatted
correctly with the API Governance CLI.

== Validate API Definitions in Design Center

You can add rulesets as dependencies to API definitions projects in
Design Center. Once added, you will see errors or warnings in the console
as you are writing your API definition.

include::design-center::partial$task-add-api-dependency.adoc[leveloffset=+1,tags=description;procedure]

== Validate Rulesets and API Definitions Using the API Governance CLI

This command allows you to test your rulesets as you are developing them to be sure your format is correct.
It can also be used to validate an API definition against a ruleset.

NOTE: API definition dependencies are not supported at this time.

=== governance validate

`> governance validate [options] <ruleset>`

This command validates the ruleset definition's format.

*Options:* 

`--spec <api-specification>`     
 
The `spec` command should be followed by an file location for an api-specification zip to validate with the ruleset.	

*Example command without api-spec:*

`governance validate ~/temp/prof-1-bad.yaml`

*Example output without api-spec for valid ruleset:*

`Ruleset conforms with Dialect`

*Example output without api-spec for non valid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

*Example command with api-spec:*

`governance validate ~/temp/prof-1.yaml --spec ~/Downloads/positive-1.0.0-raml.zip`

*Example output with a valid api-spec:*

----
Spec conforms with Ruleset

Output with a non valid api-spec:
Ruleset /path/temp/prof-1.yaml
Spec /path/Downloads/negative-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----
