= Specification Conformance

You can check for API specification conformance using a custom or MuleSoft-provided ruleset such as:

* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples

See xref:find-and-fix-conformance-issues.adoc[] for an overview of ways to validate conformance and determine why conformance failed.

[[validate-specs]]
== Validate API Specifications Against Rulesets

You can validate APIs against rulesets directly in an Anypoint Platform IDE or in a file generated by CLI regardless of whether your API is centrally governed through Anypoint API Governance. Developers or implementors typically do this either to proactively identify conformance issues or to address issues they've been asked to fix by their governance admin.

For detailed information about validating APIs against rulesets, see:

* xref:anypoint-code-builder::des-govern-api.adoc[] in the Anypoint Code Builder documentation
* xref:design-center::design-add-api-dependency.adoc#ruleset-dependencies[Ruleset Dependencies] in the Design Center documentation
* xref:anypoint-cli::api-governance.adoc#governance-api-validate[governance:api:validate] in the Anypoint CLI documentation

[[fix-conformance-issues]]
== Fix Conformance Issues

After you identify conformance issues in your specification, you can fix the issues using your IDE and publish the new version of the specification to Exchange. 

For detailed information about fixing API conformance issues, see:

* xref:anypoint-code-builder::des-govern-api.adoc#fix-conformance-issues[Fix Conformance Issues] in the Anypoint Code Builder documentation
* xref:design-center::design-add-api-dependency.adoc#ruleset-dependencies[Ruleset Dependencies] in the Design Center documentation

== See Also

* xref:monitor-api-conformance.adoc[]