= Finding API Conformance Issues in API Definitions

Governance rulesets can be applied to API definitions as you are authoring them, either in Design Center using API Designer 
or by using the API Governance CLI. You can also validate governance rulesets to make sure they are formatted correctly using the API Governance CLI.

== Validate API Definitions in Design Center

To validate APIs against governance rulesets, add the rulesets as dependencies to API specifications in Design Center API Designer. After rulesets are added, expand the *Project Errors* section to view conformance messages. 

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

== Validate API Definitions Against Governance Rulesets Using the API Governance CLI

If you prefer to use a command to validate your API definition against API Governance rulesets, use the `governance api validate` command.

=== Limitations

This command does not validate the dependencies of the API definition, such as fragments.

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-api-validate]]
== governance api validate

`> governance api validate <governance-ruleset> <api-definition-zip-file>`

This command validates the API against the rulesets it has as dependencies.

*Example command:*

`governance api validate ~/temp/prof-1.yaml ~/Downloads/positive-1.0.0-raml.zip`

*Example output:*

----
Spec conforms with Ruleset

Output with a non valid api-spec:
Ruleset /path/temp/prof-1.yaml
Spec /path/Downloads/negative-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----