= Finding API Conformance Issues in API Definitions

You can validate your API definitions against governance rulesets in Design Center
or by using the governance CLI. 

== Validate API Definitions in Design Center

To validate APIs against governance rulesets, add the rulesets as dependencies to API specifications in the Design Center API Designer text editor. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

// Screenshot of conformance validation in APID with callouts

include::partial$api-gov-apid-scap-callouts.adoc[]

[[add-rulesets]]
=== Add Rulesets to Your Project

In API Designer, you can add governance rulesets to your API projects as Exchange dependencies. 

// Reuse partial from the Design Center doc that explains the interactive guidance to add dependencies

include::design-center::partial$design-add-ruleset-dependencies.adoc[]

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

[[project-errors]]
=== Resolve Conformance Project Errors

You can use the API Designer text editor to resolve conformance project errors. See xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Definition with the Text Editor].

== Validate API Definitions Against Governance Rulesets Using the API Governance CLI

If you want to use a command to validate your API definition against governance rulesets, use the `governance api validate` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-validate,leveloffset=+1]

include::anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

== See Also

* xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project]