= Finding API Conformance Issues in API Definitions

Apply governance rulesets to API definitions as you author them, either in Design Center using API Designer 
or by using the governance CLI. You can also validate governance rulesets to make sure they are formatted correctly using the governance CLI.

== Validate API Definitions in Design Center

To validate APIs against governance rulesets, add the rulesets as dependencies to API specifications in Design Center API Designer. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

== Validate API Definitions Against Governance Rulesets Using the API Governance CLI

If you want to use a command to validate your API definition against governance rulesets, use the `governance api validate` command.

=== Limitations

This command does not validate the dependencies of the API definition, such as fragments.

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-api-validate]]
== governance api validate

`> governance api validate <governance-ruleset> <api-definition-zip-file>`

This command validates an API definition against a specified ruleset.

*Example command:*

`anypoint-cli governance api validate ~/Downloads/ruleset.yaml ~/Downloads/order-api-1.0.0-raml.zip`

*Example output:*

For a specification that is conformant to the ruleset:

----
Spec conforms with Ruleset
----

For a specification that is nonconformant to the ruleset:

----
Ruleset /path/Downloads/ruleset.yaml
Spec /path/Downloads/order-api-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----

== See Also

* xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project]