= Fixing API Specifications

To find and fix conformance issues in API specifications:

. Check for API specification conformance using a custom or MuleSoft-provided ruleset such as:
+
* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples
+
You can initiate validation of API specifications against rulesets in:
+
* <<validate-in-profiles,API Governance>> 
* <<validate-in-design-center,Design Center>> 
* <<validate-in-cli,Anypoint CLI>>
+
. After the validation, view conformance issue details using:

* <<view-spec-issues-in-report,The governance validation report>>
* <<project-errors,Design Center>>
* <<validate-in-cli,The CLI report>>
+
. Fix the conformance issues using <<project-errors,Design Center>>. 

[[validate-in-profiles]]
== Validate API Specifications in Governance Profiles
To validate APIs against governance rulesets in API Governance profiles, see xref:create-profiles.adoc[].

[[validate-in-design-center]]
== Validate API Specifications in Design Center

If your API is governed using API Governance, you can use the detailed governance report in API Governance to find any centralized governance conformance issues. If your API is not governed using API Governance or if you want to see conformance issues directly in API Designer, you can validate your API in API Designer. 

To validate APIs against governance rulesets in Design Center, add the rulesets as dependencies to API specifications in the Design Center API Designer text editor. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

// Screenshot of conformance validation in APID with callouts

include::_partials/api-gov-apid-scap-callouts.adoc[]

[[add-rulesets]]
=== Add Rulesets to Your Project

In API Designer, you can add governance rulesets to your API projects as Exchange dependencies. 

// Reuse partial from the Design Center doc that explains the interactive guidance to add dependencies

include::design-center::partial$design-add-ruleset-dependencies.adoc[]

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

[[validate-in-cli]]
== Validate API Specifications Using Anypoint CLI

To validate against rulesets using CLI without using a governance profile, use the `governance:api:validate` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-validate,leveloffset=+1]

include::anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

[[view-spec-issues-in-report]]
== View Specification Conformance Issue Details in the Governance Report

To view specification conformance issues in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Not Conformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset the API is nonconformant to. 
.. View issues for the specification only:
... Select *Specification* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset the specification is nonconformant to. 

[[project-errors]]
== Fix API Specification Issues in Design Center

After you identify conformance issues in your specification, you can fix them in API Designer and publish the new fixed version. 

See xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Specification with the Text Editor].

== See Also

* xref:design-center::design-add-api-dependency.adoc[]
* xref:monitor-api-conformance.adoc[]