= Fixing Specifications in Design Center

You can check for API specification conformance using one of the rulesets provided by MuleSoft or a custom ruleset. Some of the MuleSoft-provided rulesets that validate specification information are:

* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples

You can check specification conformance in API Governance, in Design Center, or using Anypoint CLI. 

[[validate-in-profiles]]
== Validate API Specifications in Governance Profiles
To validate APIs against governance rulesets in API Governance profiles, create or update a profile with filter criteria that defines the APIs you want to validate in its scope. You can do this in the web UI or by using Anypoint CLI commands. See xref:create-profiles.adoc[].

== Validate API Specifications Using Anypoint CLI

To validate against rulesets using CLI without using a governance profile, use the `governance:api:validate` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-validate,leveloffset=+1]

include::anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

[[view-spec-issues-in-report]]
== View Specification Conformance Issue Details in the Governance Report

To view specification conformance issues in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Nonconformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset to which the API is nonconformant. 
.. View issues for the specification only:
... Select *Specification* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset to which the specification is nonconformant. 

[[validate-in-design-center]]
== Validate API Specifications in Design Center

If your API is governed using API Governance, you can use the detailed governance report in API Governance to find any centralized governance conformance issues. If your API is not governed using API Governance or if you want to see conformance issues directly in API Designer, you can validate your API in API Designer. 

To validate APIs against governance rulesets in Design Center, add the rulesets as dependencies to API specifications in the Design Center API Designer text editor. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

// Screenshot of conformance validation in APID with callouts

include::_partials/api-gov-apid-scap-callouts.adoc[]

[[add-rulesets]]
=== Add Rulesets to Your Project

In API Designer, you can add governance rulesets to your API projects as Exchange dependencies. 

// Reuse partial from the Design Center doc that explains the interactive guidance to add dependencies

include::design-center::partial$design-add-ruleset-dependencies.adoc[]

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

[[project-errors]]
== Fix API Specification Issues in Design Center

After your specifications have been identified as nonconformant through validation by rulesets, either through centralized governance in API Governance or through ruleset dependencies in Design Center, you can fix them in API Designer. 

See xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Specification with the Text Editor].

== See Also

* xref:design-center::design-add-api-dependency.adoc[]
* xref:monitor-api-conformance.adoc[]