= Finding API Conformance Issues in API Definitions

Governance rulesets can be applied to API definitions as you are authoring them, either in Design Center using API Designer 
or by using the API Governance CLI. You can also validate governance rulesets to make sure they are formatted correctly using the API Governance CLI.

== Validate API Definitions in Design Center

To validate APIs against governance rulesets, add the rulesets as dependencies to API specifications in Design Center API Designer. After rulesets are added, expand the *Project Errors* section to view conformance messages. 

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

== Validate API Definitions Against Governance Rulesets Using the API Governance CLI

If you prefer to use a command to validate your API definition against API Governance rulesets, use the following command:

=== Limitations

This command does not validate the dependencies of the API definition, such as fragments.

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

[[governance-ruleset-validate]]
=== governance ruleset validate

`> governance validate [options] <ruleset>`

This command validates the Governance Ruleset definition's format.

*Options:* 

`--spec <api-specification>`     
 
The `spec` command should be followed by a file location for an api-specification zip to validate with the governance ruleset.	

*Example command without api-spec:*

`governance validate ~/temp/prof-1-bad.yaml`

*Example output without api-spec for valid ruleset:*

`Ruleset conforms with Dialect`

*Example output without api-spec for non valid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

*Example command with api-spec:*

`governance validate ~/temp/prof-1.yaml --spec ~/Downloads/positive-1.0.0-raml.zip`

*Example output with a valid api-spec:*

----
Spec conforms with Ruleset

Output with a non valid api-spec:
Ruleset /path/temp/prof-1.yaml
Spec /path/Downloads/negative-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----