= Finding and Fixing Conformance Issues in Specifications

You can validate API specification information using one of the rulesets provided by MuleSoft or a custom ruleset with rules that validate specification information. Some of the MuleSoft-provided rulesets that validate specification information are:

* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples

You can validate individual API specifications against governance using centralized governance configured by governance admins in API Governance, by adding rulesets as dependencies in Design Center
or by using the governance CLI. 

[[validate-in-design-center]]
== Validate API Specifications in Design Center

To validate APIs against governance rulesets directly in Design Center, add the rulesets as dependencies to API specifications in the Design Center API Designer text editor. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

// Screenshot of conformance validation in APID with callouts

include::_partials/api-gov-apid-scap-callouts.adoc[]

[[add-rulesets]]
=== Add Rulesets to Your Project

In API Designer, you can add governance rulesets to your API projects as Exchange dependencies. 

// Reuse partial from the Design Center doc that explains the interactive guidance to add dependencies

include::design-center::partial$design-add-ruleset-dependencies.adoc[]

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

[[project-errors]]
=== Fix Conformance Project Errors

To use the API Designer text editor to fix conformance project errors, see xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Specification with the Text Editor].

== Validate API Specifications Against Governance Rulesets Using the API Governance CLI

To use a command to validate your API specification against governance rulesets, use the `governance:api:validate` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-validate,leveloffset=+1]

include::anypoint-cli::partial$api-governance.adoc[tag=exchange-asset-identifier,leveloffset=+2]

== See Also

* xref:design-center::design-add-api-dependency.adoc[]
* xref:monitor-api-conformance.adoc[]