= Specification Conformance

You can check for API specification conformance using a custom or MuleSoft-provided ruleset such as:

* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples

See xref:find-and-fix-conformance-issues.adoc[] for an overview of ways to validate conformance and determine why conformance failed.

[[validate-specs]]
== Validate API Specifications Against Rulesets

You can view conformance issues directly in an Anypoint Platform IDE or in a file generated by CLI even if your API is not governed using API Governance.

For information about validating your API in Anypoint Code Builder, see xref:anypoint-code-builder::des-govern-api.adoc[].

[[validate-in-design-center]]
For information about validating your API in API Designer, see xref:design-center::design-add-api-dependency.adoc[].

[[validate-in-cli]]
=== Validate Using Anypoint CLI

To validate against rulesets using CLI without using a governance profile, use the `governance:api:validate` command.

See xref:anypoint-cli::api-governance.adoc[].

[[view-spec-issues-in-report]]
== View Specification Conformance Issue Details in the Governance Report

To view specification conformance issues in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Not Conformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset the API is nonconformant to. 
.. View issues for the specification only:
... Select *Specification* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset the specification is nonconformant to. 

[[fix-conformance-issues]]
== Fix Conformance Issues

After you identify conformance issues in your specification, you can fix the issues using your IDE and publish the new version of the specification to Exchange. 

For information about fixing your API in Anypoint Code Builder, see xref:anypoint-code-builder::des-govern-api.adoc#fix-conformance-issues[Fix Conformance Issues].

[[project-errors]]
For information about fixing your API in API Designer, see xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[].

== See Also

* xref:monitor-api-conformance.adoc[]