= Finding and Fixing Conformance Issues
:page-aliases: view-conformance-status-in-exchange.adoc
:page-notice-banner-message: Use the enhanced MuleSoft experience to manage and apply governance policies across your portfolio, with consistent strategies across providers. <a href="https://docs.mulesoft.com/general/exp-governance-work-with-strategies" target="_blank" rel="noopener">Learn More</a>

API Governance helps you continually improve your organization's API conformance by providing tools and guidance for finding and fixing conformance issues.

Governance admins typically:

* Initiate validation of APIs against rulesets in xref:create-profiles.adoc[API Governance] for all supported API aspects.
* View conformance information in the <<governance-validation-report,validation report in API Governance>>.
* Notify developers or implementors about conformance issues.

Developers and implementors typically:

* Initiate validation of API specifications against rulesets in xref:find-conformance-issues.adoc[Anypoint Code Builder or Design Center].
* View conformance information for each rule in the context of the open specification project. 

* Fix conformance issues using the following:

** xref:find-conformance-issues.adoc#fix-conformance-issues[Anypoint Code Builder or Design Center] for specifications
** xref:fix-documentation-conformance-issues.adoc[Exchange] for documentation
** xref:fix-catalog-info-conformance-issues.adoc[Exchange] for catalog information
** xref:fix-instance-conformance-issues.adoc[API Manager] for instances

Regardless of which tasks you're responsible for in governance for your organization, you can view conformance information for APIs that are centrally governed by API Governance in the following places in Anypoint Platform:

* <<governance-validation-report,Validation reports>> in API Governance or API Manager 
* <<view-conformance-in-exchange,Conformance Status pages>> in Exchange for specifications
* <<view-governed-apis-for-rulesets,Governed APIs pages>> in Exchange for rulesets

[[governance-validation-report]]
== View Conformance Information in the Validation Report

View a comprehensive governance validation report in API Governance or API Manager. 

// Screenshot of a Conformance Report page with callouts 

include::partial$api-gov-apim-governance-report.adoc[]

To view conformance information in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Not Conformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset the API is nonconformant to. 
.. View issues for a selected aspect only:
... Select an aspect of the API in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset the API is nonconformant to. 

[[view-conformance-in-exchange]]
== View Conformance Status for an API in Exchange

// Conformance status page from the Exchange doc

include::exchange::partial$task-view-conformance-status.adoc[]

// Governed apis for rulesets from the Exchange doc

[[view-governed-apis-for-rulesets]]
== View Governed APIs for a Ruleset

include::exchange::partial$task-view-governed-apis-for-rulesets.adoc[]

== Browser Resource Limits for Governance Validation

When running governance validation in the web browser, the process is subject to browser memory limits. For large or complex API specifications, the browser can exceed its resource limit and stop the validation process. In this scenario, the dialog displays a "Validation failed" error. This is expected behavior when the browser can't allocate additional resources for validation.

To avoid this limitation, run governance validation in Anypoint Code Builder Desktop, which can use more system memory and CPU than a browser tab.

== Next Steps

For more information about finding and fixing conformance specific to each API aspect, see the following:

* xref:find-conformance-issues.adoc[]
* xref:fix-instance-conformance-issues.adoc[]
* xref:fix-catalog-info-conformance-issues.adoc[]
* xref:fix-documentation-conformance-issues.adoc[]

== See Also

* xref:exchange::asset-details.adoc[]
* xref:cli-command-list.adoc[]
