= Specification Conformance

You can check for API specification conformance using a custom or MuleSoft-provided ruleset such as:

* Anypoint Best Practices
* Authentication Security Best Practices
* OpenAPI Best Practices
* AsyncAPI Best Practices
* Required Examples

See xref:find-and-fix-conformance-issues.adoc[] for an overview of ways to validate conformance and determine why conformance failed.

[[validate-specs]]
== Validate API Specifications Against Rulesets

You can validate specifications against rulesets within the context of your API project regardless of whether your API is centrally governed through Anypoint API Governance. Developers or implementors typically do this either to proactively identify conformance issues or to review issues they're notified about.

For detailed information about validating specifications against rulesets, see:

* *For Anypoint Code Builder*: xref:anypoint-code-builder::des-govern-api.adoc[]
* *For Design Center*: xref:design-center::design-add-api-dependency.adoc#ruleset-dependencies[Ruleset Dependencies]
* *For Anypoint CLI*: xref:anypoint-cli::api-governance.adoc#governance-api-validate[governance:api:validate]

[[fix-conformance-issues]]
== Fix Conformance Issues

After you identify conformance issues in your specification, you can fix the issues using your IDE and publish the new version of the specification to Exchange. 

For detailed information about fixing API conformance issues, see:

* *For Anypoint Code Builder*: xref:anypoint-code-builder::des-govern-api.adoc#fix-conformance-issues[Fix Conformance Issues]
* *For Design Center*: xref:design-center::design-add-api-dependency.adoc#ruleset-dependencies[Ruleset Dependencies] in the Design Center documentation

== See Also

* xref:monitor-api-conformance.adoc[]