= Finding API Conformance Issues in API Definitions

Governance rulesets can be applied to API definitions as you are authoring them, either in Design Center using API Designer 
or by using the API Governance CLI. You can also validate governance rulesets to make sure they are formatted
correctly using the API Governance CLI.

== Validate API Definitions in Design Center

You can add governance rulesets as dependencies to API definitions projects in API Designer. After rulesets are added, you will see errors or warnings in the console as you are writing your API definition.

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

== Validate governance rulesets and API Definitions Using the API Governance CLI

This command enables you to test your governance rulesets as you are developing them to be sure your format is correct.
It can also be used to validate an API definition against a governance ruleset.

NOTE: API definition dependencies are not supported at this time.

// include::anypoint-cli::partial$api-governance.adoc[tag=governance-validate,leveloffset=+1]

`> governance validate [options] <ruleset>`

This command validates the Governance Ruleset definition's format.

*Options:* 

`--spec <api-specification>`     
 
The `spec` command should be followed by a file location for an api-specification zip to validate with the Governance Ruleset.	

*Example command without api-spec:*

`governance validate ~/temp/prof-1-bad.yaml`

*Example output without api-spec for valid ruleset:*

`Ruleset conforms with Dialect`

*Example output without api-spec for non valid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1`

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

*Example command with api-spec:*

`governance validate ~/temp/prof-1.yaml --spec ~/Downloads/positive-1.0.0-raml.zip`

*Example output with a valid api-spec:*

----
Spec conforms with Ruleset

Output with a non valid api-spec:
Ruleset /path/temp/prof-1.yaml
Spec /path/Downloads/negative-1.0.0-raml.zip
Spec does not conform with Ruleset
[.. full report shown here..]
----