= Finding API Conformance Issues in API Definitions

Apply governance rulesets to API definitions as you author them, either in Design Center using API Designer 
or by using the governance CLI. You can also validate governance rulesets to make sure they are formatted correctly using the governance CLI.

== Validate API Definitions in Design Center

To validate APIs against governance rulesets, add the rulesets as dependencies to API specifications in Design Center API Designer. After you add the rulesets, expand the *Project Errors* section to view conformance messages. 

// Screenshot of conformance validation in APID with callouts

include::partial$api-gov-apid-scap-callouts.adoc[]

[[add-rulesets]]
=== Add Rulesets to Your Project

In API Designer, you can add governance rulesets to your API projects as Exchange dependencies. 

include::design-center::partial$apid-add-ruleset-dependencies.adoc[]

See xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project].

[[project-errors]]
=== Resolve Conformance Project Errors

You can use the API Designer text editor to resolve conformance project errors. See xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Definition with the Text Editor].

== Validate API Definitions Against Governance Rulesets Using the API Governance CLI

If you want to use a command to validate your API definition against governance rulesets, use the `governance api validate` command.

include::anypoint-cli::partial$api-governance.adoc[tag=governance-api-validate,leveloffset=+1]

== See Also

* xref:design-center::design-add-api-dependency.adoc[Adding Dependencies to an API-Specification Project]