= Fixing Instances in API Manager

You can check for API instance information conformance using a ruleset provided by MuleSoft or a custom ruleset. A ruleset provided by MuleSoft that validates API instance information is:

* Mule API Management Best Practices

After Anypoint API Governance identifies conformance issues in your API instances, you can view the governance validation report details to get information about the issues. After you identify what needs to be fixed, go to the instance in API Manager and fix the issue. If the issue is an instance-related issue in the specification, use your API editor, such as API Designer, to fix the specification. Refer to xref:find-conformance-issues.adoc[].

== View Instance Conformance Issue Details in the Governance Report

To view instance conformance issues in the governance validation report:

. Navigate to the report.
* In Anypoint API Governance:
+
.. In the API Governance console, select the *Governed APIs* tab.
.. If the *Instances* column has a *Nonconformant* badge, click *View Report* for information about the conformance issue.
* In API Manager:
.. Select the *Conformance Report* page for an instance that is marked as nonconformant.
. If the API has a *Nonconformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset to which the API is nonconformant. 
.. View issues for API instances only:
... Select *Instances* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset to which the API instances are nonconformant.

== View Rule Details in the Rulesets

If you need more information to fix the issues, open the ruleset in Exchange and view the descriptions and messages for the rules that your API doesn't conform to. 

// Screenshot of a section of the ruleset with a description of the properties 

// include::_partials/api-gov-apim-ruleset-fix-tips.adoc[]

=== Example Rules and Recommended Fixes

The following table shows some example rules and the actions to take to fix conformance to those rules:

[%header,cols="3a,3a,3a",frame=none]
|===

|Rule
|Aspect
|Recommended Fix
|<policy-name-a> policies should be configured before <policy-name-b> policies
|An instance ID
|In API Manager, rearrange the policies for the instance as suggested in the rule. 
|The API instance has no <policy-name> policy applied
|An instance ID
|In API Manager, add the specified policy to the instance.
|All API Instances server URLs should be described in the API specification
|A specification
|Edit the specification and add descriptions for all its API instance URLs.
|===

== See Also

* xref:api-manager::api-instance-landing-page.adoc[]
* xref:monitor-api-conformance.adoc[]