= Fixing API Catalog Information in Exchange

You can check for API catalog information conformance using a ruleset provided by MuleSoft or a custom ruleset. API catalog information is associated with an API asset in Exchange in the asset portal. 

A ruleset provided by MuleSoft that validates API catalog information is:

* API Catalog Information Best Practices

[[view-api-catalog-issues-in-report]]
== View API Catalog Conformance Issue Details in the Governance Report

To view API catalog conformance issues in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Not Conformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset to which the API is nonconformant. 
.. View issues for the API catalog only:
... Select *Catalog Info* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset to which the API catalog is nonconformant.

[[fix-api-catalog-issues-in-exchange]]
== Fix API Catalog Conformance Issues in Exchange

Fix issues by updating the API catalog information associated with the API so that it conforms to the rules it violated. 

For information about updating API catalog information using Exchange, refer to xref:exchange::to-describe-an-asset.adoc[].
