= Instance Conformance

You can check for API instance information conformance using a custom or MuleSoft-provided ruleset. A ruleset provided by MuleSoft that validates API instance information is:

* Mule API Management Best Practices

After Anypoint API Governance identifies conformance issues in your API instances:

. View the governance validation report to get information about the issues. 
. If the issues are in the instance configuration, fix the instance using API Manager. 
. If the issues are instance-related issues in the specification, fix the specification using Design Center.

== View Rule Details in the Rulesets

For more information about fixing the issues, open the ruleset in Exchange and view the descriptions and messages for the rules that your API doesn't conform to. 

// Screenshot of a section of the ruleset with a description of the properties 

// include::_partials/api-gov-apim-ruleset-fix-tips.adoc[]

=== Example Rules and Recommended Fixes

The following table shows some example rules and the actions to take to fix conformance to those rules:

[%header,cols="3a,3a,3a",frame=none]
|===

|Rule
|Aspect
|Recommended Fix
|<policy-name-a> policies should be configured before <policy-name-b> policies
|An instance ID
|In API Manager, rearrange the policies for the instance as suggested in the rule. 
|The API instance has no <policy-name> policy applied
|An instance ID
|In API Manager, add the specified policy to the instance.
|All API Instances server URLs should be described in the API specification
|A specification
|Edit the specification and add descriptions for all its API instance URLs.
|===

== See Also

* xref:api-manager::govern-api-instances.adoc[]
* xref:monitor-api-conformance.adoc[]
* xref:find-conformance-issues.adoc[]