= Fixing Conformance Issues in API Instances

After API Governance identifies conformance issues in your API instances, you can fix them in API Manager. 

== Find Nonconformant Instances in API Governance

To find nonconformant instances in API Governance:

. In the API Governance console, select the *Governed APIs* tab.
. If the Instances column has a *Nonconformant* badge, click *View Report* for information about the conformance issue.

// Screenshot of a Conformance Report page with callouts 

include::_partials/api-gov-apim-governance-report.adoc[]

== Fix Conformance Issues in API Manager

To fix instance conformance issues in API Manager:

. Select the *Conformance Report* page for the API that is marked as nonconformant.
. View the messages to see what you need to do and click the link to API Manager to fix the issue.
. If the nonconformance messages don't have enough detail to help you fix the issue, open the ruleset for the offending rule and view the documentation for that ruleset to get the information you need.
+
// Screenshot of a section of the ruleset with a description of the properties 

include::_partials/api-gov-apim-ruleset-fix-tips.adoc[]

== See Also

// * xref:api-manager::xxx.adoc[xxx]
* xref:find-conformance-issues.adoc[]
* xref:monitor-api-conformance.adoc[]