= Fixing API Catalog Information in Exchange

You can validate API catalog information using a ruleset provided by MuleSoft or a custom ruleset with rules that validate API catalog information. API catalog information is associated with an API asset in Exchange in the asset portal. 

A ruleset provided by MuleSoft that validates API catalog information is:

* API Catalog Information Best Practices

[[view-api-catalog-issues-in-report]]
== View API Catalog Conformance Issue Details in the Governance Report

To view API catalog conformance issues in the governance validation report:

. In the API Governance console, select the *Governed APIs* tab.
. If the API has a *Nonconformant* badge, click *View Report* for information about the conformance issue.
.. View all issues:
+
Click *View Details* for a ruleset to which the API is nonconformant. 
.. View issues for the API catalog only:
... Select *Catalog Info* in the Conformance Breakdown section of the report.
... Click *View Details* for a ruleset to which the API catalog is nonconformant.

[[fix-api-catalog-issues-in-exchange]]
== Fix API Catalog Conformance Issues in Exchange

//Update the following to reuse this from Exchange doc 

Fix API Catalog information conformance issues as follows:

. In Exchange, navigate to the API that has catalog information conformance issues.

. Click the edit pen icon in the asset portal.
+
You can change the asset icon, name, description, contact name, and contact email.

.. To change the icon, click the edit pen icon, select an image file, and then click *Open*.
.. To change the asset portal name, enter the new asset portal name.
.. To change the description, enter a new asset description in the *Description* field.
.. To change the contact name or email, enter a new contact name and email in the corresponding field.
. To cancel the changes, click the X icon.
. To save the changes, click the check icon.

For more details about updating API catalog information in Exchange, refer to xref:exchange::to-describe-an-asset.adoc[].
