= Getting Started with API Governance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

API Governance enables you to:

* *Share governance best practices:* Publish governance rulesets in Anypoint Exchange to share with other developers.
* *Apply consistent rules at design time:* Enable developers to apply governance rulesets at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automatically apply standards to your API contract and definition within your CI/CD pipeline.

== Before You Begin

To access the API Governance console:

* MuleSoft must activate API Governance for your Anypoint Platform organization.

* You must have the *Anypoint API Governance administrator* permission set by your Anypoint Platform administrator. 

== Govern Your APIs

.Govern your APIs using the following steps: 

. xref:install-cli.adoc[(Optional) Install the API Governance CLI] to run commands locally or in automation tools.

. xref:add-tags.adoc[Identify] the APIs that you want to govern.

. xref:create-profiles.adoc[Configure governance profiles] to identify which rulesets to apply to which APIs.
+
Add profiles in the API Governance console or using the governance CLI to group and apply rulesets to sets of APIs. 

. xref:monitor-api-conformance.adoc[Monitor governance conformance status] in the API Governance console.

. xref:find-conformance-issues.adoc[Find and fix conformance issues] as you author in Design Center API Designer.

. xref:view-conformance-status-in-exchange.adoc[View conformance status] for a selected API in Exchange. 
+
When you view a governed API asset in Exchange, select the *Conformance Status* page to view conformance information for that API.

== See Also

* xref:access-management::managing-permissions.adoc[Managing Permissions in Access Management]
// * xref:anypoint-cli::install.adoc[Installing Anypoint CLI]
* xref:exchange::to-describe-an-asset.adoc#add-and-remove-asset-tags[Adding and Removing Asset Tags in Exchange]