= Getting Started with Anypoint Anypoint API Governance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

With Anypoint Anypoint Anypoint API Governance you can:

* *Share governance best practices:* Publish governance rulesets in Anypoint Exchange to share with other developers.
* *Apply consistent rules at design time:* Enable developers to apply governance rulesets at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automatically apply standards to your API contract and definition within your CI/CD pipeline.

== Before You Begin

To access the Anypoint API Governance console:

* MuleSoft must activate Anypoint API Governance for your Anypoint Platform organization.

* You must have the *Anypoint API Governance administrator* permission set by your Anypoint Platform administrator. 

* If you plan to use the API Governance CLI, you must install it on the systems where you run local commands or where your automated tools, such as CI/CD pipelines or scripts, are executed.

.Govern your APIs using the following steps: 

. xref:add-tags.adoc[Limit governance] to just the APIs that you want to govern.
+
To limit governance to sets of APIs you are ready to govern, add tags to APIs in Exchange. This ensures that notifications are sent only to the API owners who have been informed and are ready to begin making their APIs conformant to your conformance profiles.

. xref:create-profiles.adoc[Configure governance profiles] to identify which rulesets to apply to which APIs.
+
Add profiles in the API Governance console or using the governance CLI to group and apply rulesets to sets of APIs. 

. xref:monitor-api-conformance.adoc[Monitor governance conformance status] in the API Governance console.
+
The API Governance console enables you to monitor and report on your organization's conformance success and failure. You can send notifications from the console to API authors to inform them that they need to update their API definitions to meet standards. 

. xref:find-conformance-issues.adoc[Find conformance issues] as you author in Design Center or by using the Anypoint API Governance CLI.
+
You can add governance rulesets as dependencies to API definitions projects in Design Center API Designer. After rulesets are added, messages are shown in the *Project Errors* section of API Designer
as you are writing your API definition. You can also validate governance ruleset format and API definition conformance using the Anypoint API Governance CLI.

. xref:create-custom-rulesets.adoc[Create custom rulesets] and upload them to Exchange.
+
MuleSoft provides several commonly-used rulesets. If you want
to add custom governance rulesets to Exchange, you can download and modify the provided rulesets and upload the custom rulesets to Exchange in the same way you download and upload other assets. 

== See Also

* xref:access-management::managing-permissions.adoc[Managing Permissions in Access Management]
// * xref:anypoint-cli::install.adoc[Installing Anypoint CLI]
* xref:exchange::to-describe-an-asset.adoc#add-and-remove-asset-tags[Adding and Removing Asset Tags in Exchange]