ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

= Getting Started with Anypoint API Governance
:page-notice-banner-message: Use the enhanced MuleSoft experience to manage and apply governance policies across your portfolio, with consistent strategies across providers. <a href="https://docs.mulesoft.com/general/exp-governance-work-with-strategies" target="_blank" rel="noopener">Learn more</a>.

[NOTE]
We updated the terminology in the API Governance UI to reflect a broader range of asset types. Where Governance previously used "APIs," it now uses "Services." There are no changes to functionality. During this transition, you'll see a mix of the new and previous terms in our documentation.


After you become familiar with the UI and concepts covered in the xref:index.adoc[Anypoint API Governance Overview], you're ready to get started governing your APIs.

== Before You Begin

Before you begin using API Governance, see the following sections:

* <<verify-permissions>>
* <<opt-in>>
* <<third-party-gateway-prereqs>>

[[verify-permissions]]
=== Verify Your Permissions

To use API Governance, you need either _Governance Viewer_ or _Governance Administrator_ permission.

* *API Governance* > *Governance Viewer*
+
This permission allows API Governance users, such as API developers and architects, to:

** View the Governance console conformance summary.
** View the *Governed Services* page with the list of governed services that they have permission to view.
** Download a detailed governance report for their APIs in CSV format.
+
* *API Governance* > *Governance Administrator*
+
This permission allows API Governance users, such as API governance and security officers, full access to API Governance.

Anypoint Platform organization administrators are allowed full access to API Governance regardless of their API Governance permission settings.

Higher level permissions override the *Governance Viewer* permission. If a user has the *Governance Administrator* permission or is an organization administrator, setting the *Governance Viewer* permission for them does not limit their permissions.

[[opt-in]]
=== Opt in to Additional Functionality

If you're an administrator and have an opt-in banner in the Governance console, opt in to get additional functionality for your business groups (organizations). See the xref:release-notes::api-governance/api-governance-release-notes.adoc##oct-17-2023[API Governance Release Notes entry for October, 17 2023].

This documentation covers the full product functionality that is available after the opt-in.

[[third-party-gateway-prereqs]]
=== Set Up Third-Party Gateway Connectivity (Optional)

If you manage APIs on third-party gateways, connect those providers before you begin governing their APIs.

[NOTE]
====
Connecting third-party gateway providers is available only in the enhanced MuleSoft experience. For the complete setup procedure, see xref:general::exp-governance-setup-third-party-providers.adoc[].
====

== Govern Your APIs

Govern your APIs using these steps:

. xref:add-tags.adoc[Identify] APIs to filter for governance by using tags and categories in Exchange.

. xref:create-profiles.adoc[Configure governance profiles] to identify which rulesets to apply to which APIs.
.. Consider saving your profiles as draft to test settings before revealing their targeted APIs' conformance information across Anypoint Platform.
.. After you test settings using draft profiles, xref:create-profiles.adoc#activate-draft-profile[activate the profiles] to notify developers and reveal the resulting conformance information across Anypoint Platform.

. xref:monitor-api-conformance.adoc[Monitor governance conformance status] in the Governance console.
** View the APIs targeted by each draft profile to assess conformance impacts for that profile and download the associated CSV file report.
** View summary information in the Governance console and in validation reports.

. xref:find-and-fix-conformance-issues.adoc[Find and fix conformance issues]:
* In API specifications in Anypoint Code Builder, Design Center, and Exchange as you design your APIs
* In API instances in API Manager at deployment time
* In API catalog information in Exchange asset portal information
* In API documentation in Exchange asset portal documentation

. xref:create-custom-rulesets.adoc[(Optional) Create custom rulesets] to more effectively govern APIs for your business groups (organizations).

. xref:cli-command-list.adoc[(Optional) Install and run CLI commands] to automate governance as part of your CI/CD pipeline and to more easily create custom rulesets.

. (Optional) Use the API Governance Experience API to implement custom API-based solutions that access a subset of API Governance functionality. For example, you can use the experience API to list governance profiles and retrieve API conformance status information. Access the experience API in Exchange in your preferred Anypoint Platform control plane:

** https://anypoint.mulesoft.com/exchange/68ef9520-24e9-4cf2-b2f5-620025690913/api-governance-xapi[US]
** https://eu1.anypoint.mulesoft.com/exchange/e0b4a150-f59b-46d4-ad25-5d98f9deb24a/api-governance-xapi[EU]

[[govern-third-party-apis]]
== Govern Third-Party APIs

If your organization runs APIs on third-party gateways, API Governance provides a workflow to connect providers, govern APIs alongside MuleSoft APIs, and export compliance reports.

[NOTE]
====
The complete workflow for governing third-party APIs is available only in the enhanced MuleSoft experience. For detailed steps, see xref:general::exp-governance-govern-third-party-apis.adoc[].
====

== See Also

* xref:access-management::managing-permissions.adoc[]
* xref:cli-command-list.adoc[]
* xref:index.adoc[]
