= Getting Started with Anypoint API Governance

After you become familiar with the UI and concepts covered in the xref:index.adoc[Anypoint API Governance Overview], you are ready to get started governing your APIs.

== Before You Begin

=== Permissions

Ensure you have access to the API Governance console with one of the following permissions:

* *API Governance* > *Governance Viewer*
+
With this permission, API Governance users, such as API developers and architects, can view:

** The list of governed APIs that they have permission to view.
** A detailed governance report for their APIs.
+
* *API Governance* > *Governance Administrator*
+
With this permission, API Governance users, such as API governance and security officers, have full view and administrative access to API Governance.

=== Opt in to Additional Functionality
 
If you have an opt-in banner in the API Governance console, opt in to get additional functionality. See the xref:release-notes::api-governance/api-governance-release-notes.adoc##oct-17-2023[API Governance Release Notes entry for October, 17 2023].

If you don't see the opt-in banner, you already have access to the new functionality.

This documentation is written for the full product functionality that is available after the opt-in.

== Govern Your APIs

Govern your APIs using the following steps:

. xref:install-cli.adoc[(Optional) Install Anypoint CLI] to run `governance` commands locally or in automation tools.

. xref:add-tags.adoc[Identify] the APIs that you want to govern.

. xref:create-profiles.adoc[Configure governance profiles] to identify which rulesets to apply to which APIs.

. xref:monitor-api-conformance.adoc[Monitor governance conformance status] in the API Governance console.

. xref:find-conformance-issues.adoc[Find and fix conformance issues in specifications] in API Designer and Exchange as you design your APIs. 

. xref:find-conformance-issues.adoc[Find and fix conformance issues in instances] in API Manager at deployment time.

. xref:create-custom-rulesets.adoc[(Optional) Create custom rulesets]  to more effectively govern APIs for your business groups (organizations).

== See Also

* xref:access-management::managing-permissions.adoc[]
* xref:cli-command-list.adoc[]
* xref:index.adoc[]