= Getting Started with Anypoint API Governance

After you become familiar with the UI and concepts covered in the xref:index.adoc[Anypoint API Governance Overview], you are ready to get started governing your APIs.

== Before You Begin

Before you begin using API Governance:

* <<verify-permissions>>
* <<opt-in>>

[[verify-permissions]]
=== Verify Your Permissions

Ensure you have access to API Governance with one of the following permissions:

* *API Governance* > *Governance Viewer*
+
This permission allows API Governance users, such as API developers and architects, to:

** View the API Governance console conformance summary 
** View the *Governed APIs* page with the list of governed APIs that they have permission to view
** Download a detailed governance report for their APIs in CSV format.
+
* *API Governance* > *Governance Administrator*
+
This permission allows API Governance users, such as API governance and security officers, full access to API Governance. 

Anypoint Platform organization administrators are allowed full access to API Governance regardless of their API Governance permission settings. 

The *Governance Viewer* permission is overridden by higher level permissions. If a user has the *Governance Administrator* permission or is an organization administrator, setting the *Governance Viewer* permission for them does not limit their permissions.

[[opt-in]]
=== Opt in to Additional Functionality
 
If you're an administrator and have an opt-in banner in the API Governance console, opt in to get additional functionality for your business groups (organizations). See the xref:release-notes::api-governance/api-governance-release-notes.adoc##oct-17-2023[API Governance Release Notes entry for October, 17 2023].

This documentation is written for the full product functionality that is available after the opt-in.

== Govern Your APIs

Govern your APIs using the following steps:

. xref:install-cli.adoc[(Optional) Install Anypoint CLI] to run `governance` commands locally or in automation tools.

. xref:add-tags.adoc[Identify] the APIs that you want to govern.

. xref:create-profiles.adoc[Configure governance profiles] to identify which rulesets to apply to which APIs.

. xref:monitor-api-conformance.adoc[Monitor governance conformance status] in the API Governance console.

. xref:find-conformance-issues.adoc[Find and fix conformance issues in specifications] in API Designer and Exchange as you design your APIs. 

. xref:find-conformance-issues.adoc[Find and fix conformance issues in instances] in API Manager at deployment time.

. xref:create-custom-rulesets.adoc[(Optional) Create custom rulesets] to more effectively govern APIs for your business groups (organizations).

== See Also

* xref:access-management::managing-permissions.adoc[]
* xref:cli-command-list.adoc[]
* xref:index.adoc[]