= Anypoint API Governance Overview
:page-aliases: api-gov.adoc

Anypoint API Governance is a component of Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. 

With Anypoint API Governance you can:

* Improve your organization's API quality:
+
Identify conformance issues in governed APIs and take steps to resolve them.
+
* Share and enforce governance best practices:
+
Customize and publish governance rulesets to share and enforce organization-specific best practices with your developers.
+
* Apply consistent rules from design time to deployment:
+
Use governance rulesets to apply centralized governance to multiple aspects of your APIs, from specifications at design time to instances at deployment.
+
* Enforce governance within your DevOps organization:
+
Automate API governance in your CI/CD pipeline using CLI commands or through API solutions using the experience API.

// == Anypoint API Governance Overview Video 

// Watch the Anypoint API Governance Product Spotlight video to see a quick overview of Anypoint API Governance.

// ++++
//include::_partials/api-gov-gs-video.html[]
//++++

== Governance Dashboard

The API Governance Dashboard offers an organization-wide view of your API landscape, allowing you to quickly grasp the overall status of your APIs and identify areas that require attention. It serves as a starting point for understanding your API governance posture and taking initial steps to improve it.

From the API Governance Dashboard, you can:

*  View metrics, such as the number of unprotected APIs, governed APIs, APIs in Exchange, and APIs in production.
*  Understand the distribution of your APIs by type, including REST API, AsyncAPI, and HTTP API.
*  Get insights into your API governance posture, including conformance status and nonconformance severity for governed APIs.
*  Take action from the Dashboard based on the presented metrics, such as initiating the creation of new governance profiles to start governing unprotected APIs and navigating to lists of APIs for further review.

See xref:api-governance-dashboard-overview.adoc[] for details.

== Governance Console

In the API Governance console, governance administrators can:

* Create <<gov-profiles,governance profiles>> to apply <<gov-rulesets,governance rulesets>> to a targeted set of APIs. The API Governance console then provides a conformance summary for all of your validated APIs.
* Monitor API conformance and notify developers to help improve conformance.

See xref:api-governance-console.adoc[] for details.

== Governance Across Anypoint Platform

In addition to viewing API conformance information in the API Governance console, developers, architects, and implementors can view governance conformance information and take action to fix issues using:

[[exchange-overview]]
* Exchange

** Developers can view conformance status details for published API specifications, discover rulesets, and publish custom rulesets. 
** Implementors can view rulesets to determine how to fix API instance conformance issues.

[[design-center-overview]]
* Anypoint Code Builder and Design Center:

** Developers or architects can check API specification conformance in the API design phase by applying governance rulesets directly to API specifications as dependencies. 

[[api-manager-overview]]
* API Manager:

** Implementors can check API instance conformance by viewing comprehensive governance reports. 

== Anypoint API Governance Concepts

Following are the concepts you must know to use Anypoint API Governance.

// Definition of Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=governance-profiles]

// Definition of Active Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-active-profiles]

// Definition of Draft Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-draft-profiles]

// Definition of Governance Rulesets

include::general::partial$api-gov-concepts.adoc[tag=governance-rulesets]

// Definition of Governed APIs

include::general::partial$api-gov-concepts.adoc[tag=governed-apis]

// Definition of API

include::general::partial$api-gov-concepts.adoc[tag=api-entire]

// Definition of API Aspects

include::general::partial$api-gov-concepts.adoc[tag=api-aspects]

// Definition of API Specifications

include::general::partial$api-gov-concepts.adoc[tag=api-specifications]

// Definition of API Implementation

include::general::partial$api-gov-concepts.adoc[tag=api-implementation]

// Definition of API Instances

include::general::partial$api-gov-concepts.adoc[tag=api-instances]

// Definition of API Documentation

include::general::partial$api-gov-concepts.adoc[tag=api-documentation]

// Definition of API Catalog Information

include::general::partial$api-gov-concepts.adoc[tag=api-catalog-info]

== See Also

* xref:get-started.adoc[]
* xref:general::glossary.adoc[]