= API Governance Overview

Anypoint API Governance is a component of the Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. API Governance helps you improve your organization's API quality by enabling you to identify conformance issues and take steps to resolve them.

API Governance enables you to:

* *Share governance best practices:* Publish governance rulesets in Anypoint Exchange to share with other developers.
* *Apply consistent rules at design time:* Enable developers to apply governance rulesets at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automatically apply standards to your API contract and definition within your CI/CD pipeline.

// View the following video for a brief overview of API Governance.  

++++
include::_partials/api-gov-gs-video.html[]
++++

== Governance Console

In the API Governance console, you add <<gov-rulesets,_governance rulesets_>> to <<gov-profiles,_governance profiles_>> to apply the governance rulesets to multiple APIs across your organization. The API Governance console then provides you with an overview of conformance for all validated APIs.
You can monitor your APIs' conformance and notify developers to help improve the conformance.

// Screenshot of the console with callouts

include::_partials/api-gov-console-scap-callouts.adoc[]

API Governance is integrated with these other components of Anypoint Platform:

* Anypoint Design Center, where governance rulesets are applied to API definitions (as dependencies)

* Anypoint Exchange, where governance rulesets are cataloged and discovered

API developers or architects can apply the governance rulesets directly to API definitions as dependencies in API Designer during the API design phase.

// Screenshot of conformance validation in APID with callouts

include::partial$api-gov-apid-scap-callouts.adoc[]

== API Governance Concepts

Following are the concepts you need to know to use API Governance.

// Definition of Governance Profiles

include::_partials/api-gov-concepts.adoc[tag=governance-profiles,leveloffset=+2]

// Definition of Governance Profile Status

include::_partials/api-gov-concepts.adoc[tag=governance-profile-status,leveloffset=+2]

// Definition of Governance Rulesets

include::_partials/api-gov-concepts.adoc[tag=governance-rulesets,leveloffset=+2]

// How to discover rulesets in Exchange

include::partial$api-gov-ruleset-discovery.adoc[]

// Definition of Governed APIs

include::_partials/api-gov-concepts.adoc[tag=governed-apis,leveloffset=+2]

// Definition of API Conformance

include::_partials/api-gov-concepts.adoc[tag=api-conformance,leveloffset=+2]

// Definition of API Conformance Status

include::_partials/api-gov-concepts.adoc[tag=api-conformance-status,leveloffset=+2]

// Definition of Nonconformance Severity

include::_partials/api-gov-concepts.adoc[tag=nonconformance-severity,leveloffset=+2]

// Definition of Project Errors

include::_partials/api-gov-concepts.adoc[tag=project-errors,leveloffset=+2]

// Definition of API Governance Usage Reports

include::_partials/api-gov-concepts.adoc[tag=api-governance-usage-reports,leveloffset=+2]

== See Also

* xref:get-started.adoc[Getting Started with API Governance]