= Anypoint API Governance Overview
:page-aliases: api-gov.adoc
:page-notice-banner-message: Use the enhanced MuleSoft experience to manage and apply governance policies across your portfolio, with consistent strategies across providers. <a href="https://docs.mulesoft.com/general/exp-governance-work-with-strategies" target="_blank" rel="noopener">Learn more</a>.

[NOTE]
We updated the terminology in the API Governance UI to reflect a broader range of asset types. Where Governance previously used "APIs," it now uses "Services." There are no changes to functionality. During this transition, this documentation includes a mix of the new and previous terms.


Anypoint API Governance is a component of Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle.

With Anypoint API Governance:

* Improve your company's API quality:
+
Identify conformance issues in governed APIs and take steps to resolve them.
+
* Share and enforce governance best practices:
+
Customize and publish governance rulesets to share and enforce company-specific best practices with your developers.
+
* Apply consistent rules from design time to deployment:
+
Use governance rulesets to apply centralized governance to multiple aspects of your APIs, from specifications at design time to instances at deployment.
+
* Enforce governance within your DevOps organization:
+
Automate API governance in your CI/CD pipeline with CLI commands or through API solutions with the experience API.

// == Anypoint API Governance Overview Video 

// Watch the Anypoint API Governance Product Spotlight video to see a quick overview of Anypoint API Governance.

// ++++
//include::partial$api-gov-gs-video.html[]
//++++

== Governance Dashboard

The API Governance Dashboard offers an organization-wide view of your API landscape. Review the overall status of your APIs, identify areas that require attention, and take steps to improve your governance posture.

From the API Governance Dashboard:

* View metrics, such as the number of unprotected APIs, governed APIs, APIs in Exchange, and APIs in production.
* Understand the distribution of your APIs by type, including REST API, AsyncAPI, HTTP API, gRPC, Agent, and MCP.
* Understand your governance posture, including conformance status and nonconformance severity for governed APIs.
* Take action from the Dashboard based on the presented metrics, such as creating new governance profiles to govern unprotected APIs and viewing lists of APIs for further review.

See xref:dashboard-overview.adoc[] for details.

== Governance Console

In the Governance console, governance administrators can:

* Create <<gov-profiles,governance profiles>> to apply <<gov-rulesets,governance rulesets>> to a targeted set of APIs. The Governance console then provides a conformance summary for all of your validated APIs.
* Monitor conformance and notify developers to help improve conformance.

See xref:api-governance-console.adoc[] for details.

== Governance Across Anypoint Platform

In addition to viewing conformance information in the governance console, developers, architects, and implementors can view governance conformance information and take action to fix issues using:

[[exchange-overview]]
* Exchange

** Developers can view conformance status details for published API specifications, discover rulesets, and publish custom rulesets. 
** Implementors can view rulesets to determine how to fix API instance conformance issues.

[[design-center-overview]]
* Anypoint Code Builder and Design Center:

** Developers or architects can check API specification conformance in the API design phase by applying governance rulesets directly to API specifications as dependencies. 

[[api-manager-overview]]
* API Manager:

** Implementors can check API instance conformance by viewing comprehensive governance reports. 

== Anypoint API Governance Concepts

These are the key concepts for using Anypoint API Governance.

// Definition of Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=governance-profiles]

// Definition of Active Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-active-profiles]

// Definition of Draft Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-draft-profiles]

// Definition of Governance Rulesets

include::general::partial$api-gov-concepts.adoc[tag=governance-rulesets]

// Definition of Governed APIs

include::general::partial$api-gov-concepts.adoc[tag=governed-apis]

// Definition of API

include::general::partial$api-gov-concepts.adoc[tag=api-entire]

// Definition of API Aspects

include::general::partial$api-gov-concepts.adoc[tag=api-aspects]

// Definition of API Specifications

include::general::partial$api-gov-concepts.adoc[tag=api-specifications]

// Definition of API Implementation

include::general::partial$api-gov-concepts.adoc[tag=api-implementation]

// Definition of API Instances

include::general::partial$api-gov-concepts.adoc[tag=api-instances]

// Definition of API Documentation

include::general::partial$api-gov-concepts.adoc[tag=api-documentation]

// Definition of API Catalog Information

include::general::partial$api-gov-concepts.adoc[tag=api-catalog-info]

== See Also

* xref:get-started.adoc[]
* xref:general::glossary.adoc[]
