= Anypoint API Governance Overview
:page-aliases: api-gov.adoc

Anypoint API Governance is a component of Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. 

With Anypoint API Governance you can:

* Improve your organization's API quality:
+
Identify conformance issues in governed APIs and take steps to resolve them.
+
* Share and enforce governance best practices:
+
Customize and publish governance rulesets to share and enforce organization-specific best practices with your developers.
+
* Apply consistent rules from design time to deployment:
+
Use governance rulesets to apply centralized governance to multiple aspects of your APIs, from specifications at design time to instances at deployment.
+
* Enforce governance within your DevOps organization:
+
Automate API governance in your CI/CD pipeline using CLI commands or through API solutions using the experience API.

== Anypoint API Governance Overview Video 

Watch the Anypoint API Governance Product Spotlight video to see a quick overview of Anypoint API Governance.

++++
include::_partials/api-gov-gs-video.html[]
++++

== Governance Console

In the API Governance console, governance administrators can:

* Add <<gov-rulesets,governance rulesets>> to <<gov-profiles,governance profiles>> to apply the governance rulesets to multiple APIs across their organizations. The API Governance console then provides an overview of conformance for all of your validated APIs.
* Monitor API conformance and notify developers to help improve conformance.
* Create draft profiles and view insights to assess API conformance for various selected rulesets without actually governing the APIs and without revealing the conformance status throughout Anypoint Platform. No notifications are sent for draft profiles.
* Activate draft profiles when they're ready to govern the targeted APIs.
Saving a profile as active:

** Triggers the API validation
** Sends notifications (if enabled) to developers to help them make the APIs conformant to the selected rulesets.
** Populates the insights on the governance console with the newly active profiles' data.

// Screenshot of the console with callouts

include::_partials/api-gov-console-scap-callouts.adoc[]

== Governance Across Anypoint Platform

In addition to viewing API conformance information in the API Governance console, developers, architects, and implementors can view governance conformance information and take action to fix issues using:

[[exchange-overview]]
* Exchange

** Developers can view conformance status details for published API specifications, discover rulesets, and publish custom rulesets. 
** Implementors can view rulesets to determine how to fix API instance conformance issues.

[[design-center-overview]]
* Design Center API Designer:

** Developers or architects can check API specification conformance in the API design phase by applying governance rulesets directly to API specifications as dependencies. 

[[api-manager-overview]]
* API Manager:

** Implementors can check API instance conformance by viewing comprehensive governance reports. 

== Anypoint API Governance Concepts

Following are the concepts you must know to use Anypoint API Governance.

// Definition of Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=governance-profiles]

// Definition of Active Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-active-profiles]

// Definition of Draft Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=gov-draft-profiles]

// Definition of Governance Rulesets

include::general::partial$api-gov-concepts.adoc[tag=governance-rulesets]

// Definition of Governed APIs

include::general::partial$api-gov-concepts.adoc[tag=governed-apis]

// Definition of API Conformance

include::general::partial$api-gov-concepts.adoc[tag=api-conformance]

// Definition of API Conformance Status

include::general::partial$api-gov-concepts.adoc[tag=api-conformance-status]

// Definition of Nonconformance Severity

include::general::partial$api-gov-concepts.adoc[tag=nonconformance-severity]

// Definition of Governance Status

include::general::partial$api-gov-concepts.adoc[tag=governance-status]

// Definition of Governance Profile Status

include::general::partial$api-gov-concepts.adoc[tag=governance-profile-status]

// Definition of Project Errors

include::general::partial$api-gov-concepts.adoc[tag=project-errors]

// Definition of API

include::general::partial$api-gov-concepts.adoc[tag=api-entire]

// Definition of API Aspects

include::general::partial$api-gov-concepts.adoc[tag=api-aspects]

// Definition of API Specifications

include::general::partial$api-gov-concepts.adoc[tag=api-specifications]

// Definition of API Implementation

include::general::partial$api-gov-concepts.adoc[tag=api-implementation]

// Definition of API Instances

include::general::partial$api-gov-concepts.adoc[tag=api-instances]

// Definition of API Documentation

include::general::partial$api-gov-concepts.adoc[tag=api-documentation]

// Definition of API Catalog Information

include::general::partial$api-gov-concepts.adoc[tag=api-catalog-info]

== See Also

* xref:get-started.adoc[]
* xref:general::glossary.adoc[]