= Anypoint API Governance Overview
:page-aliases: api-gov.adoc

Anypoint API Governance is a component of the Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. 

With API Governance you can:

* *Improve your organization's API quality:* Identify conformance issues in governed APIs and take steps to resolve them.
* *Share and enforce governance best practices:* Customize and publish governance rulesets to share and enforce organization-specific best practices with your developers.
* *Apply consistent rules at design time:* Apply governance rulesets at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automate API governance using CLI commands in your CI/CD pipeline.

////

View the following video for a brief overview of API Governance.  

Watch the API Governance Product Spotlight video to see a quick overview of API Governance.

++++
include::_partials/api-gov-gs-video.html[]
++++

////

== Governance Console

In the API Governance console, add <<gov-rulesets,_governance rulesets_>> to <<gov-profiles,_governance profiles_>> to apply the governance rulesets to multiple APIs across your organization. The API Governance console then provides you with an overview of conformance for all validated APIs.
You can monitor your APIs' conformance and notify developers to help improve the conformance.

// Screenshot of the console with callouts

include::_partials/api-gov-console-scap-callouts.adoc[]

== Governance in Exchange, Design Center, and API Manager

API Governance is integrated with <<exchange-overview>>, <<design-center-overview>>, and <<api-manager-overview>>.

[[exchange-overview]]
=== Exchange

In Exchange:

* Developers can view conformance status details for published API specifications, discover rulesets, and publish custom rulesets. 
* Implementors can view rulesets to determine how to fix API instance conformance issues.

[[design-center-overview]]
=== Design Center

In Design Center API Designer:

* Developers or architects can check API specification conformance in the API design phase by applying governance rulesets directly to API specifications as dependencies. 
* Use the *Project Errors* section for information about where the issue is in the specification and how to fix it.

// Screenshot of conformance validation in APID with callouts

include::_partials/api-gov-apid-scap-callouts.adoc[]

[[api-manager-overview]]
=== API Manager

In API Manager:

* Implementors can check API instance conformance by viewing the comprehensive governance report. 

// Screenshot of a Conformance Report page with callouts 

include::_partials/api-gov-apim-governance-report.adoc[]

== API Governance Concepts

Following are the concepts you need to know to use API Governance.

// Definition of Governance Profiles

include::_partials/api-gov-concepts.adoc[tag=governance-profiles,leveloffset=+2]

// Definition of Governance Profile Status

include::_partials/api-gov-concepts.adoc[tag=governance-profile-status,leveloffset=+2]

// Definition of Governance Rulesets

include::_partials/api-gov-concepts.adoc[tag=governance-rulesets,leveloffset=+2]

// How to discover rulesets in Exchange

include::_partials/api-gov-ruleset-discovery.adoc[]

// Definition of Governed APIs

include::_partials/api-gov-concepts.adoc[tag=governed-apis,leveloffset=+2]

// Definition of Governance Status

include::_partials/api-gov-concepts.adoc[tag=governance-status,leveloffset=+2]

// Definition of API Conformance

include::_partials/api-gov-concepts.adoc[tag=api-conformance,leveloffset=+2]

// Definition of API Conformance Status

include::_partials/api-gov-concepts.adoc[tag=api-conformance-status,leveloffset=+2]

// Definition of Nonconformance Severity

include::_partials/api-gov-concepts.adoc[tag=nonconformance-severity,leveloffset=+2]

// Definition of Project Errors

include::_partials/api-gov-concepts.adoc[tag=project-errors,leveloffset=+2]

// Definition of API Governance Usage Reports

include::_partials/api-gov-concepts.adoc[tag=api-governance-usage-reports,leveloffset=+2]

== See Also

* xref:get-started.adoc[Getting Started with API Governance]