= API Governance Overview
:page-aliases: api-gov.adoc

Anypoint API Governance is a component of the Anypoint Platform that
enables you to apply governance rules to your APIs as part of the
API lifecycle. 

With API Governance you can:

* *Improve your organization's API quality:* Identify conformance issues in published API specifications and instances and take steps to resolve them.
* *Share governance best practices:* Publish governance rulesets in Anypoint Exchange to share with other developers.
* *Apply consistent rules at design time:* Apply governance rulesets at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automate API conformance validation within your CI/CD pipeline using the Anypoint CLI `governance` commands.

////

View the following video for a brief overview of API Governance.  

Watch the API Governance Product Spotlight video to see a quick overview of API Governance.

++++
include::_partials/api-gov-gs-video.html[]
++++

////

== Governance Console

In the API Governance console, add <<gov-rulesets,_governance rulesets_>> to <<gov-profiles,_governance profiles_>> to apply the governance rulesets to multiple APIs across your organization. The API Governance console then provides you with an overview of conformance for all validated APIs.
You can monitor your APIs' conformance and notify developers to help improve the conformance.

// Screenshot of the console with callouts

include::_partials/api-gov-console-scap-callouts.adoc[]

== Governance in Exchange, Design Center, and API Manager

API Governance is integrated with API Manager, Exchange, and Design Center. 

* In API Manager, implementors can check API instance conformance by viewing comprehensive validation reports. 

* In Exchange:
** Developers can view published API specifications' conformance status details, discover provided rulesets, and publish custom rulesets. 
** Implementors can view the ruleset that the instance failed for details on how to fix API instance conformance issues.

* In Design Center API Designer, developers or architects can check API specification conformance in the API design phase by applying governance rulesets directly to API specifications as dependencies. Use the *Project Errors* section for information on where the issue is in the specification and how to fix it.

// Screenshot of conformance validation in APID with callouts

include::_partials/api-gov-apid-scap-callouts.adoc[]

== API Governance Concepts

Following are the concepts you need to know to use API Governance.

// Definition of Governance Profiles

include::general::partial$api-gov-concepts.adoc[tag=governance-profiles,leveloffset=+2]

// Definition of Governance Profile Status

include::general::partial$api-gov-concepts.adoc[tag=governance-profile-status,leveloffset=+2]

// Definition of Governance Rulesets

include::general::partial$api-gov-concepts.adoc[tag=governance-rulesets,leveloffset=+2]

// Definition of Governed APIs

include::general::partial$api-gov-concepts.adoc[tag=governed-apis,leveloffset=+2]

// Definition of Governance Status

include::general::partial$api-gov-concepts.adoc[tag=governance-status,leveloffset=+2]

// Definition of API Conformance

include::general::partial$api-gov-concepts.adoc[tag=api-conformance,leveloffset=+2]

// Definition of API Conformance Status

include::general::partial$api-gov-concepts.adoc[tag=api-conformance-status,leveloffset=+2]

// Definition of Nonconformance Severity

include::general::partial$api-gov-concepts.adoc[tag=nonconformance-severity,leveloffset=+2]

// Definition of Project Errors

include::general::partial$api-gov-concepts.adoc[tag=project-errors,leveloffset=+2]

// Definition of API Governance Usage Reports

include::general::partial$api-gov-concepts.adoc[tag=api-governance-usage-reports,leveloffset=+2]

// Definition of API

include::general::partial$api-gov-concepts.adoc[tag=api-entire,leveloffset=+2]

// Definition of API Aspects

include::general::partial$api-gov-concepts.adoc[tag=api-aspects,leveloffset=+2]

// Definition of API Specifications

include::general::partial$api-gov-concepts.adoc[tag=api-specifications,leveloffset=+3]

// Definition of API Implementation

include::general::partial$api-gov-concepts.adoc[tag=api-implementation,leveloffset=+3]

// Definition of API Instances

include::general::partial$api-gov-concepts.adoc[tag=api-instances,leveloffset=+3]

// Definition of API Documentation

include::general::partial$api-gov-concepts.adoc[tag=api-documentation,leveloffset=+3]

// Definition of API Catalog Information

include::general::partial$api-gov-concepts.adoc[tag=api-catalog-info,leveloffset=+3]

== See Also

* xref:get-started.adoc[Getting Started with API Governance]