= Monitoring API Conformance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create your first Governance Profile, the API Governance console will
show various statuses to keep you apprised of your governance posture.
You can also access this information from the command line using various commands.

== View Governance Profile Statuses

A Governance Profile has two statuses, Normal and At Risk, which are based on
the percentage of conformant APIs in the profile.

* *Normal:* More than 70% of APIs are conformant.
* *At Risk:* Less than 70% of APIs are conformant.

== View API Conformance Across Governance Profiles

APIs are API definitions that are catalogued in Exchange as REST APIs.

API conformance status indicates whether the API definitions that are included in
your Governance Profiles pass all applied governance rulesets.

* *Conformant:* The APIs pass all applied governance rulesets.
* *Not Conformant:* The APIs fail at least one governance ruleset.
* *Not Validated:* The APIs are not validated because they are not included in a Governance Profile.

== View Nonconformance by Severity Across Governance Profiles

Nonconformance severity is categorized by the percentage of passed governance rulesets among all applied governance rulesets.

* *High Severity:* 0 - 40% Governance rulesets passed
* *Medium Severity:* 41% - 80% Governance rulesets passed
* *Low Severity:* 81% - 99% Governance rulesets passed

== Send Notifications to API Authors

IMPORTANT: Notification emails can only be sent if the API owner has added a contact email address
to the API in Exchange. 

When you notice an API is not conformant, you can take action by sending the API owner an email.
The notification email includes the name of the API(s) that are not conformant, which governance ruleset(s)
failed, and the number and types of rules that were failed (violation, warning, info). 

NOTE: Emails can be sent to API owners even when there are no conformance issues with the API. 

To send a notification email to the API owner: 

. Log in to Anypoint Platform using an account that has the API Governance Administrator permission.
. In the navigation bar or the main Anypoint Platform page, click *API Governance*.
. Select a Governance Profile Name that is At Risk. 
. Click the Notify Owner icon.
. Review the email text and click *Notify Owner*.

== Export Reports

You can export multiple different reports depending on the page where you click the Export Report button.

On the main API Governance console page, on the Profiles tab, you can export a report that shows all of the Governance Profiles
and their corresponding organization ids as well as the following information about the Governance Profiles: 

* Governance Profile Ids
* status
* total APIs governed
* number of conformant APIs
* number of nonconformant APIs
* time stamps
* associated tags

On the main API Governance console page, on the APIs tab, you can export a report that shows all of the APIs
currently being governed and their corresponding organization ids as well as the following information about the APIs: 

* API Id
* versions
* total number of APIs
* number of conformant APIs
* number of nonconformant APIs
* time stamps

On specific Governance Profile pages, you can export a report that shows the following information about the specific Governance Profile: 

* the organization Id
* API Ids
* versions
* total number of APIs
* number of conformant APIs
* number of nonconformant APIs
* time stamps
