= Monitoring API Conformance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create your first governance profile, the API Governance console will
show various statuses to keep you apprised of your governance conformance.
You can also access this information from the command line using various commands.

== View Governance Profile Statuses

A governance profile has two statuses, Normal and At Risk, which are based on
the percentage of conformant APIs in the profile.

* *Normal:* More than 70% of APIs are conformant.
* *At Risk:* Less than 70% of APIs are conformant.

== View API Conformance Across Governance Profiles

APIs are API definitions that are published in Exchange as REST APIs.

API conformance status indicates whether the API definitions that are included in
your governance profiles pass all applied governance rulesets.

* *Conformant:* The APIs pass all applied governance rulesets.
* *Not Conformant:* The APIs fail at least one governance ruleset.
* *Not Validated:* The APIs are not validated because they are not included in a governance profile.

== View Nonconformance by Severity Across Governance Profiles

Nonconformance severity is categorized by the percentage of passed governance rulesets among all applied governance rulesets.

* *High Severity:* 0 - 40% Governance rulesets passed
* *Medium Severity:* 41% - 80% Governance rulesets passed
* *Low Severity:* 81% - 99% Governance rulesets passed

== Export Reports

You can export multiple different reports depending on the page where you click the Export Report button.

On the main API Governance console page, on the Profiles tab, you can export a report that shows all of the governance profiles
and their corresponding organization ids as well as the following information about the governance profiles: 

* governance profile Ids
* status
* total APIs governed
* number of conformant APIs
* number of nonconformant APIs
* time stamps
* associated tags

On the main API Governance console page, on the APIs tab, you can export a report that shows all of the APIs
currently being governed and their corresponding organization ids as well as the following information about the APIs: 

* API Id
* versions
* total number of APIs
* number of conformant APIs
* number of nonconformant APIs
* time stamps

On specific governance profile pages, you can export a report that shows the following information about the specific governance profile: 

* the organization Id
* API Ids
* versions
* total number of APIs
* number of conformant APIs
* number of nonconformant APIs
* time stamps
