= Monitoring API Conformance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you configure governance profiles for your APIs and the resulting governance data is available, you can monitor and report on your organization's REST API definitions' conformance success and failure.  

== Status Information on the Console

You can view the latest status information on the console.

Governance Profile Statuses::

You can view profile statuses in the console. Governance profile statuses are based on the percentage of conformant APIs in the profile:

* *Normal:* More than 70% of APIs are conformant.
* *At Risk:* Less than 70% of APIs are conformant.

API Conformance Across Governance Profiles::

API conformance status indicates whether the API definitions that are included in your governance profiles pass all applied governance rulesets:

* *Conformant:* The APIs pass all applied governance rulesets.
* *Not Conformant:* The APIs fail at least one governance ruleset.
* *Not Validated:* The APIs are not validated because they are not included in a governance profile.

Nonconformance by Severity Across Governance Profiles::

Nonconformance severity is categorized by the percentage of passed governance rulesets among all applied governance rulesets:

* *High Severity:* 0 - 40% Governance rulesets passed
* *Medium Severity:* 41% - 80% Governance rulesets passed
* *Low Severity:* 81% - 99% Governance rulesets passed

== Reports

You can export reports from the console by clicking the `Export Report` button beside the type of information you want to export.

Governance Profile Report::
On the main API Governance console page, on the `Profiles` tab, you can export a report of governance profile information, such as: 

* Organization ID 
* Governance profile IDs
* Status
* Total APIs governed
* Number of conformant APIs
* Number of nonconformant APIs
* Timestamps
* Associated tags

Governed API Report::
On the main API Governance console page, on the *APIs* tab, you can export a report that shows your governed APIs' information, such as:  

* Organization ID 
* API ID
* Versions
* Total number of APIs
* Number of conformant APIs
* Number of nonconformant APIs
* Timestamps

Specific Profile Report::
On a selected governance profile page, you can export a report that shows the selected governance profile's information, such as: 

* Organization ID
* API IDs
* Versions
* Total number of APIs
* Number of conformant APIs
* Number of nonconformant APIs
* Time stamps