= Publishing Discovered APIs to Exchange

You can publish discovered APIs' specifications to Exchange.

To publish a discovered API to Exchange:

. In API Governance, select *API Discovery*.
. Select the *Discovered APIs* tab. 
. For the API you want to publish, select *Review and Publish*.
. Select corresponding tabs to view the API's catalog information, specification, and instance information.
.. You can review and add or change catalog information in the *Catalog info* page.
.. You can review the specification in the *Specification* page.
.. You can review the instance mapping in the *Instances* page. See <<view-api-declaration>>.
. When you are ready to publish, click *Save and Publish*.

// Are the spec and instance published anywhere they can see?

[[view-api-declaration]]
== View the Mapping of API Information from AWS to Anypoint Platform

API Discovery maps your AWS API properties to Anypoint Platform API properties by making opinionated assumptions about what the AWS properties represent. API information is represented in Anypoint Platform by a proprietary Anypoint Platform API declarative language. 

Not all AWS APIs properties have an equivalent in Anypoint Platform, so a subset of the properties are mapped.

When you select a discovered APIs, the details show the API properties in the raw declarative language. This is view only and is generated by during API discovery during the scan.

The following examples show how the sections of the generated API declaration map to the equivalent in AWS.

[[api-environment-declaration]]
=== AWS Environment Information

The AWS environment cannot be mapped directly to an equivalent in API Discovery, because an AWS environment has a different meaning and purpose than an Anypoint Platform environment. Therefore, API Discovery maps the AWS environment to a tag in the discovered API.

The following example shows how the AWS environment information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: Environment <2>
metadata: <3>
  name: v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of environment is saved as AWS metadata in API Discovery because there isn't an equivalent in Anypoint Platform.
.. Metadata from the AWS API.

[[api-environment-binding-declaration]]
=== AWS Environment Binding Information

The AWS environment cannot be mapped directly to an equivalent in API Discovery.

The following example shows how AWS environment binding information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: EnvironmentBinding <2>
spec:
  targetEnvironmentRef: <2>
    name: v1-rcizkl
  targetRef: <3>
    name: uqzxgsgcg6-v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of API binding from the AWS API.
.. Target environment reference from AWS.
.. Target spec reference from AWS.

[[api-policy-binding-declaration]]
=== AWS Policy Bindings Information

The AWS policy bindings information is shown in the declaration.

The following example shows how AWS services information is represented in the API declaration for a discovered API. If there are multiple services, there is a section for each one. This example just shows one.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: Service <2>
metadata:
  name: uqzxgsgcg6-/history-get-service <3>
  labels: <4>
    aws.amazon.com/arn: arn:AWS:apigateway:US_EAST_2::/restapis/uqzxgsgcg6/resources/cx8i3f/methods/get/integration
    aws.amazon.com/region: us-east-2
    aws.amazon.com/resourceId: cx8i3f
    aws.amazon.com/method: get
    aws.amazon.com/partition: AWS
    aws.amazon.com/resource: apigateway-integration
spec:
  address: MOCKED
----
[calloutlist]
.. API version from the AWS API.
.. Kind of service from the AWS API.
.. Service name in AWS.
.. Labels.

[[api-services-declaration]]
=== AWS Services Information

The AWS services information is shown in the declaration.

The following example shows how AWS policy binding information is represented in the API declaration for a discovered API. If there are multiple policy bindings, there is a section for each one. This example just shows one.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: PolicyBinding <2>
metadata:
  name: uqzxgsgcg6-v1-rcizkl-account-level-rate-limiting <3>
spec:
  policyRef:
    name: aws-rate-limiting <4>
  config:
    burstLimit: 5000 <5>
    rateLimit: 10000.0 <6>
  order: 1
  targetRef:
    name: uqzxgsgcg6-v1-rcizkl
----
[calloutlist]
.. API version from the AWS API.
.. Kind of policy binding from the AWS API.
.. Policy metadata name in AWS.
.. Policy reference name in AWS.
.. Burst limit.
.. Rate limit.


[[api-instance-declaration]]
=== API Instance Information

APIs might have multiple instances. Each instance is represented by its own section in the API declaration.

The following example shows how AWS instance information is represented in the API declaration for a discovered API.

----
apiVersion: gateway.mulesoft.com/v1alpha1 <1>
kind: ApiInstance <2>
metadata: <3>
  name: uqzxgsgcg6-v1-rcizkl
  labels:
    aws.amazon.com/id: uqzxgsgcg6
    aws.amazon.com/resource: apigateway
    aws.amazon.com/stage: v1
    mulesoft.com/apiinstance-id: v1
    aws.amazon.com/region: us-east-2
    aws.amazon.com/partition: AWS
    aws.amazon.com/endpointConfiguration: REGIONAL
spec: <4>
  address: https://uqzxgsgcg6.execute-api.us-east-2.amazonaws.com/v1
----
[calloutlist]
.. API version from the AWS API.
.. Kind of API from the AWS API.
.. Metadata from the AWS API.
.. Specification URL address in AWS based on the AWS API information and region used to authenticate to API Discovery.

== Troublehoot Publish Issues

Some reasons for publish process to fail or complete with issues or warnings might be:

* Insufficient permissions.
+ 
Solution: Ensure that your permissions are set as detailed in xref:identify-apis-from-external-sources.adoc[].
* A network or internet drop when you start the publish. This runs in the background in the cloud, so is not highly likely. 
+ 
Solution: Ensure that your network and internet are connected and stable. 
* Invalid credentials entered in the API Discovery *API Sources* > <API Source> > *Authenticate* page.
+
Solution: Verify your credentials in AWS and then edit the API source and reenter them in the *Authenticate* page.

== See Also

* xref:exchange::about-sharing-assets.adoc[]