= Publishing Discovered APIs to Exchange

// Include overview of why you should publish

include::_partials/api-discovery-options-overview.adoc[]

== Publish an API to Exchange

To publish a discovered API to Exchange:

. In API Governance, select *API Discovery*.
. Select the *Discovered APIs* tab. 
. For the API you want to publish, select *Review and Publish*.
. Select corresponding tabs to view the API's catalog information, specification, and instance information.
.. You can review and add or change catalog information in the *Catalog info* page.
+
Update catalog information as needed to override the default mapping, such as API version and API name.
.. You can review the specification in the *Specification* page.
+ 
The OAS specification from AWS is used.
.. You can review the instance mapping in the *Instances* page. 
+
In the sidebar, select the instance stage you want to review. The stage name from AWS is shown in the name. For example, instance_dev, instance_prod, and instance_qax. 
. When you are ready to publish the API, click *Save and Publish*.
+
APIs you publish to Exchange are no longer shown in the *Discovered APIs* page. 

For details on the AWS to Anypoint Platform API mapping, see xref:api-discovery-declaration-ref.adoc[].

== Troubleshoot Publish Issues

Some reasons for publish process to fail or complete with issues or warnings might be:

* Insufficient permissions.
+ 
Solution: Ensure that your permissions are set as detailed in xref:identify-apis-from-external-sources.adoc[].
* A network or internet drop when you start the publish. This runs in the background in the cloud, so is not highly likely. 
+ 
Solution: Ensure that your network and internet are connected and stable. 
* Invalid credentials entered for the API source.
+
Solution: Verify your credentials in AWS and then edit the API source and reenter them in the *Authenticate* page. See xref:add-api-source.adoc[].

== See Also

* xref:exchange::about-sharing-assets.adoc[]
* xref:api-discovery-declaration-ref.adoc[]