= Creating Custom Rulesets

For the Beta, we have added MuleSoft Anypoint API Best Practices,
OpenAPI Best Practices, OWASP API Security Top 10, and Authentication
Security Best Practices rulesets to Exchange in advance. 

== Write Rulesets using AML

In the future, we will provide links to documentation for writing your own custom rulesets
using AML (Anything Modeling Language), a declarative language for defining metadata
documents that can be parsed into graphs of information.

For more information on AML, see https://a.ml/docs/aml/aml[What is AML?,,role=external,window=_blank].

== Create Ruleset Zip File with the CLI

This command generates a zip file that can be used in Exchange asset upload with the `--files.docs.zip` option.

=== governance document

`> governance document [options] <ruleset> <file>`

This command creates a ruleset definition zip file.

*Example command:*
`governance document ~/temp/prof-1.yaml ~/temp/prof-1.doc.zip`

*Example output:*

----
validation name [ 'scalar-parameters' ]
Saving to /Users/suntersander/temp/prof-1.doc.zip
----

== Create Custom Ruleset Assets in Anypoint Exchange

If you want to create custom rulesets in Exchange, you would create them as any other asset.

include::exchange::partial$task-create-asset.adoc[leveloffset=+1,tags=description;procedure]


=== Create Custom Rulesets in Anypoint Exchange with the CLI

Ruleset upload is completed using Exchange commands and only type was added.

*Example command:*

`anypoint-cli exchange asset uploadv2 --name "cli ruleset asset 1" --description "cli ruleset asset 1 description" --properties.apiVersion v1 --properties.mainFile ruleset-validation.yaml --files.ruleset.yaml /Users/janedoe/temp/ruleset-validation.yaml cli-ruleset-asset/1.1.2 --files.docs.zip ~/temp/ruleset.doc.zip`
