= Viewing Conformance Status in Exchange 

You can view conformance status in Exchange for APIs that are validated by API Governance. If an API is validated:

* A conformance badge is displayed for a selected API version.
* A *Conformance* column shows conformance for each validated version of the API in the *Manage Versions* page. 
* A *Conformance Status* page appears for all REST APIs and AsyncAPIs. If a selected version of an API has been validated against governance rulesets, the conformance status page gives conformance information and gives options to fix nonconformant versions.

To view conformance status in Exchange:

. Select an API asset in Exchange. 

. Review the conformance badge.
+
. To see conformance by version, click *Manage Versions*.
+
Review the *Conformance* column, which shows the governance conformance status for each validated version.
+
. To view conformance details, select *Conformance Status* in the navigation bar.
From the conformance status page, you can:
+
* Select the version of the API that you want to view.
* View the lists of centralized governance rulesets and additional rulesets against which the API has been validated.
** If there are more rulesets than are shown on the initial page, click the *Show All* link to show the full list.
** Click the external link icon beside a ruleset to view that ruleset's page in Exchange. 
* For nonconformant APIs, click *Fix the API Definition* and then select one of the following:
** *Fix Using Design Center*
+ 
After your API definition opens in Design Center, add the listed rulesets as dependencies and view the conformance messages in the *Project Errors* section to fix and republish your API definition.
** *Fix Using Anypoint CLI*
+
Follow the prompts on the page to copy, update, and run the Anypoint CLI commands to add the listed rulesets as dependencies and fix and republish your API definition.

== See Also

* xref:exchange::asset-details.adoc[Asset Details]
* xref:find-conformance-issues.adoc[Finding API Conformance Issues in API Definitions]
* xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Definition with the Text Editor]
* xref:cli-command-list.adoc[List of API Governance CLI Commands]