= Viewing Conformance Status in Exchange 

You can view conformance status in Exchange for APIs that are validated by API Governance. If an API is validated:

* A conformance badge is displayed for a selected API version.
* A *Conformance* column shows conformance for each validated version of the API in the *Manage Versions* page. 
* A *Conformance Status* page gives conformance details. If an API that has been validated against a centralized governance ruleset is nonconformant, a conformance status page appears in Exchange for that API. 

To view conformance status in Exchange:

. Select an API asset in Exchange. 

. Review the conformance badge beside the lifecycle state badge.
+
. To see conformance by version, click *Manage Versions*.
+
Review the *Conformance* column, which shows the governance conformance status for each validated version.
+
. To view conformance details, select the *Conformance Status* page in the left navigation.
From the conformance status page, you can:
+
* Select the version of the API that you want to view.
* View the lists of centralized governance rulesets and additional rulesets against which the API has been validated.
* For nonconformant APIs, select from one of the following to update the API and republish it to make it conformant:
** *Fix Using the CLI*
** *Fix Using Design Center*
* Click external link icons beside listed rulesets to view the ruleset asset's page in Exchange.

== See Also

* xref:exchange::asset-details.adoc[Asset Details]
* xref:design-center::design-create-publish-api-raml-editor.adoc#the-editor[Create an API Specification with the Text Editor].