// Partial reused in index.adoc and monitor-api-conformance.adoc

// tag::governance-profiles[]

[[gov-profiles]]
= Governance Profiles

A governance profile applies chosen governance rulesets to a select group of APIs. The API definitions are validated
against the governance rulesets.

// end::governance-profiles[]

// tag::governance-profile-status[]

[[gov-profile-status]]
= Governance Profile Status

You can view profile statuses in the console. Governance profile statuses are based on the percentage of conformant APIs in the profile:

* *Normal:* More than 70% of APIs are conformant.
* *At Risk:* Less than 70% of APIs are conformant.

// end::governance-profile-status[]

// tag::governance-rulesets[]

[[gov-rulesets]]
= Governance Rulesets

Governance rulesets are collections of rules, or guidelines, that can be applied over the metadata extracted from API definitions in the Anypoint Platform. Some examples of governance rulesets are internal and external best
practice guidelines, such as naming conventions, and industry-specific government standards, such as making sure your APIs that have sensitive data are encrypted (HTTPS).

// end::governance-rulesets[]

// tag::governed-apis[]

[[governed-apis]]
= Governed APIs

APIs are governed if they are identified by the selection criteria of at least one of the governance profiles. If an API is governed, all versions of that API are considered one governed API. Subscription limits are set based on your organization's purchased capacity and the UI gives information on usage and alerts when you are nearing or exceeding your subscription capacity. 

// end::governed-apis[]

// tag::governance-status[]

[[governance-status]]
= Governance Status

Governance status on the console shows the number of governed APIs, total number of APIs of supported API types, and subscription limit information.

// end::governance-status[]

// tag::api-conformance[]

[[api-conformance]]
= API Conformance

API conformance indicates whether a validated API definition passes all of the required rules in one or more governance rulesets. If an API definition is included in multiple governance profiles, it must pass all of the rulesets in all of those profiles to be conformant.

// end::api-conformance[]

// tag::api-conformance-status[]

[[conformance-status]]
= API Conformance Status

API conformance status indicates whether the API definitions that are included in your governance profiles pass all applied governance rulesets: 

* *Conformant:* The APIs pass all applied governance rulesets.
* *Not Conformant:* The APIs fail at least one governance ruleset.
* *Not Validated:* The APIs are not validated because they are not included in a governance profile.

Versions of an API might have different conformance statuses. Total version conformance status counts are shown in the API Governance console and conformance status indicators are shown for API versions in API Governance and in Exchange. 

NOTE: API conformance applies only to API types supported by API Governance, such as REST API and AsyncAPI. 

// end::api-conformance-status[]

// tag::nonconformance-severity[]

[[nonconformance-severity]]
= Nonconformance Severity

Nonconformance severity is categorized by percentage of passed rulesets among all required rulesets.

High Severity:: 0 - 40% rulesets passed

Medium Severity:: 41% - 80% rulesets passed

Low Severity:: 81% - 99% rulesets passed

// end::nonconformance-severity[]

// tag::project-errors[]

[[project-errors]]
= Project Errors

Project errors are shown in the Design Center API Designer text editor page. The *Project Errors* section of the page shows functional issues and nonconformance messages found in the API definition that is open in the text editor.

// end::project-errors[]

// tag::api-governance-usage-reports[]

[[api-governance-usage-reports]]
= API Governance Usage Reports

You can view usage reports to gain insight into your monthly usage of API Governance. See xref:general::usage-reports.adoc#api-governance[Viewing Usage Reports for API Governance].

// end::api-governance-usage-reports[]